### DISCUSSION TITLE
Variables in hooks

### DISCUSSION THREAD

**Discussion by pixelmultiplo** [welaika/wordmove#630] [Ideas]
Is it possible to know, in hooks, what we just did? 
I would like to notify in Slack what a user did and on which website, so i need access to the parameters used in the command line (-pdwu for instance) and the url of the target.

**Comment by alessandro-fazzi** [comment]
Hi @marekmaurizio ,

ATM you can do a nice trick in order to have the URL: said that `hooks` is a per-environment configuration, you can do something like:

```yml
production:
  <% prod_url = "http://sshwordmove.welaika.com" %>
  vhost: <%= prod_url %>
  wordpress_path:  '/var/www/spam' # use an absolute path here

  [...]

  hooks:
    push:
      after:
        local:
          - 'curl -X "POST" "https://welaika.ryver.com/application/webhook/XXXXXXXXXXX" -H "Content-Type: text/plain; charset=utf-8" -d "Deploy su <%= prod_url %> terminato! :spock-hand:"'
```

> note that it is a real-life example :P

Command line flags instead aren't accessible. Precisely: when `movefile.yml` is loaded and parsed (hence applying the logic inside ERB tags) user's command line flags are not there and they could even not being received by the program yet.

This would be a totally new feature to design from ground up. Inside the class managing hooks execution, we have the flags passed by the user inside a hash:

```
[1] (pry) Wordmove::Hook: 0> cli_options
=> {"uploads"=>true, "db"=>true, "languages"=>true, "wordpress"=>true}
```

That said I don't know - yet? - how to use them to produce something useful. Since I'd like to do real needs driven development, I'd ask if you mind to write down some examples about the interface you'd expect.

The only approach I can imagine at the moment is to use magic placeholders, e.g.:

```yml
hooks:
    push:
      after:
        local:
          - 'curl -X "POST" "https://welaika.ryver.com/application/webhook/XXXXXXXXXXX" -H "Content-Type: text/plain; charset=utf-8" -d "Deploy su <%= prod_url %> terminato! :spock-hand: \n Options used: %COMMAND_LINE_OPTIONS%"'
```

expecting Wordmove to to a substitution on the `%COMMAND_LINE_OPTIONS%` placeholder, using a dictionary, with a simple string

```
[2] (pry) Wordmove::Hook: 0> cli_options.keys.join(', ')
=> "uploads, db, languages, wordpress"
```

obtaining

```
'curl -X "POST" "https://welaika.ryver.com/application/webhook/XXXXXXXXXXX" -H "Content-Type: text/plain; charset=utf-8" -d "Deploy su <%= prod_url %> terminato! :spock-hand: \n Options used: uploads, db, languages, wordpress"'
```

Do you have better examples/ideas? Honestly I do not think this could be a priority feature, but a nice one, potentially opening in the future to extending the placeholders' dictionary and bringing more functionality to our beloved hooks, hence I'd take it in serious consideration.

I hope to have helped you out a bit. Looking forward to receive your feedback.
