### DISCUSSION TITLE
Database connection refused with push and --all, but -d works

### DISCUSSION THREAD

**Discussion by n8sb** [welaika/wordmove#647] [Q&A]
Running into an odd error.  When pushing to staging with '--all', everything pushed until it gets to the db and I get the error below.  If I run with -d by itself or with other flags individually, It pushed no problem.

Any input appreciated.

**error output**
```
▬▬ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

   remote | mysqldump --host=[secret] --user=wordpress --password=[secret] --result-file="[secret]wp-content/dump.sql" wp_f1rst_staging
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:64:in `connect': Connection refused - connect(2) for 159.203.191.61:22 (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:64:in `connect_internal'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:137:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:641:in `block in tcp'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:227:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:227:in `foreach'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/socket.rb:631:in `tcp'
	from /Library/Ruby/Gems/2.6.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:73:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/photocopier-1.4.1/lib/photocopier/ssh.rb:71:in `session'
	from /Library/Ruby/Gems/2.6.0/gems/photocopier-1.4.1/lib/photocopier/ssh.rb:44:in `exec!'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:66:in `remote_run'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:79:in `download_remote_db'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh/default_sql_adapter.rb:8:in `backup_remote_db!'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:37:in `push_db'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:116:in `block in push'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:40:in `block in handle_options'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `handle_options'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:115:in `push'
	from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>' 
```

**movefile.yml**
```
global:
  sql_adapter: default

local:
  vhost: "http://f1rst.local"
  wordpress_path: "/Users/natebennett/Local\ Sites/f1rst/app/public/" # use an absolute path here

  database:
    name: "local"
    user: "root"
    password: "root" # could be blank, so always use quotes around
    host: "localhost"
    mysqldump_options: '--socket "/Users/natebennett/Library/Application\ Support/Local/run/5w_uuyXS1/mysql/mysqld.sock"'
    mysql_options: '--socket "/Users/natebennett/Library/Application\ Support/Local/run/5w_uuyXS1/mysql/mysqld.sock"'

staging:
  vhost: "https://staging.xxx"
  wordpress_path: "/var/www/staging.xxx/html/" # use an absolute path here

  database:
    name: "xxx"
    user: "xxx"
    password: "xxx"
    host: "localhost"

  exclude:
    - ".htaccess"
    - ".git/"
    - ".gitignore"
    - ".gitmodules"
    - ".env"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "movefile"
    - "movefile.yml"
    - "movefile.yaml"
    - "wp-config.php"
    - "wp-content/*.sql.gz"
    - "*.orig"
    - "wp-content/plugins/cache-enabler/"

  ssh:
    host: 159.203.191.61
    user: "root"
    port: 22

production:
  vhost: "https://xxx"
  wordpress_path: "/var/www/xxx/html/" # use an absolute path here

  database:
    name: "xxx"
    user: "xxx"
    password: "xxx"
    host: "localhost"

  exclude:
    - ".htaccess"
    - ".htpasswd"
    - ".git/"
    - ".gitignore"
    - ".gitmodules"
    - ".env"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "movefile"
    - "movefile.yml"
    - "movefile.yaml"
    - "wp-config.php"
    - "wp-content/*.sql.gz"
    - "wp-content/plugins/cache-enabler/"
    - "*.orig"

  ssh:
    host: 159.203.191.61
    user: "root"
    port: 22
```
