### DISCUSSION TITLE
Ruby error when pushing database over FTP

### DISCUSSION THREAD

**Discussion by chrilleferna** [welaika/wordmove#663] [Q&A]
I frequently use wordmove with SSH on several sites without problem. For one site I only have FTP access and I run into problem when pushing the database; plugins and themes work fine.

Extract from the Movefile:

```
global:
  sql_adapter: "wpcli"
  
local:
  vhost: "http://localhost/......./www"
  wordpress_path: "/Users/chr.....ine/www" # use an absolute path here

  database:
    name: "cuisine"
    user: "cuisine"
    password: "..."
    host: "localhost"

...

production:
  vhost: "https://cui....s.com"
  wordpress_path: "/web" # use an absolute path here

  database:
    name: "c1c...aire"
    user: "c1...aire"
    password: "e...Aj"
    host: "localhost"

...

  ftp:
    user: "ccm..idaire"
    password: "e....89Aj"
    host: "CC...et "
    passive: true
    scheme: "ftp" # default "ftp"
```

Console output:

```
wordmove push -e production -d

▬▬ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

   remote | write [secret]/wp-content/dump.php
Traceback (most recent call last):
	30: from /Users/christer/.rvm/rubies/ruby-2.7.0/bin/wordmove:23:in `<main>'
	29: from /Users/christer/.rvm/rubies/ruby-2.7.0/bin/wordmove:23:in `load'
	28: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
	27: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	26: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	25: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	24: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	23: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:115:in `push'
	22: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `handle_options'
	21: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `each'
	20: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:40:in `block in handle_options'
	19: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:116:in `block in push'
	18: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ftp.rb:19:in `push_db'
	17: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ftp.rb:118:in `download_remote_db'
	16: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ftp.rb:90:in `remote_put'
	15: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/photocopier-1.4.1/lib/photocopier/adapter.rb:12:in `put'
	14: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/photocopier-1.4.1/lib/photocopier/ftp.rb:18:in `put_file'
	13: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/photocopier-1.4.1/lib/photocopier/ftp.rb:47:in `session'
	12: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/photocopier-1.4.1/lib/photocopier/ftp.rb:47:in `new'
	11: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/photocopier-1.4.1/lib/photocopier/ftp/session.rb:15:in `initialize'
	10: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:175:in `open'
	 9: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:175:in `new'
	 8: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:278:in `initialize'
	 7: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:384:in `connect'
	 6: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
	 5: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
	 4: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:386:in `block in connect'
	 3: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:348:in `open_socket'
	 2: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/socket.rb:632:in `tcp'
	 1: from /Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/socket.rb:227:in `foreach'
/Users/christer/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/socket.rb:227:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
```

What am I missing?
