### ISSUE TITLE
siteurl and Home issue

### ISSUE THREAD

**Issue by yumyo** [welaika/wordmove#12]
Hi, 
I'm facing a strange problem pushing changes to remote host, siteurl and Home DB fields are updated with the local values. Everything else, including post, are ok.
Any suggestion?

This my Movefile content:

``` yaml
local:
  vhost: "http://xxx.dev"
  wordpress_path: "/Users/xxx/Sites/xxx"
  database:
    name: "retyper"
    username: "retyper"
    password: "retyper"
    host: "localhost"
remote:
  vhost: "http://xxx.com"
  wordpress_path: "/var/www/vhosts/xxx.com/httpdocs"
  exclude:
    - .git
    - .DS_Store
    - .sass-cache
    - Movefile
  database:
    name: "xxx"
    username: "xxx"
    password: "xxx"
    host: "localhost"
  ssh:
    username: "xxx"
    host: "xxx.xx.xxx.xxx"
    # port: 22 # Port is optional
```
