### ISSUE TITLE
Executing arbitrary code in remote/local on push/pull

### ISSUE THREAD

**Issue by joeguilmette** [welaika/wordmove#142]
I was thinking that it would be really neat to be able to have wordmove execute commands before or after a push or pull, dependent on environment. With this functionality, Wordmove will be become instantly more extensible and able to integrate with just about any other tool or API.

This could be configured in the Movefile like so:

```
production: #environment

[...]

  push: # on push to production
    remote: # execute the following in the production environment
      before: # before wordmove pushes
        - "php /etc/scripts/do-this-before-push.php" # execute code that exists on remote
      after:  # after push is complete
        - "sudo find /var/www/*/htdocs/ -type f -exec chmod 0675 {} \;" # help out with permissions on production after push
    local: # execute the following locally
      after:
        - "/etc/scripts/slackupdate.sh 'project' '@channel: Push to production by Joe' 'api/from/service'" # notify a Slack channel that a push has to production from a user has been made

  pull: # on pull from production
    local:
      after: 
        - "php /etc/scripts/dothisonpull.php" # execute code that exists on remote
        - "/etc/scripts/slackupdate.sh 'project' 'Pull from production by Joe' 'api/from/service'" # post in a Slack channel that a pull from local to production by a user has been made

```

And an example script (local:/etc/scripts/slackupdate.sh) to accompany the above Movefile:

```
#!/bin/bash

echo 'Sending update to #$0'
curl -X POST --data-urlencode 'payload={"channel": "#$0", "username": "Wordmove", "text": "$1"}' https://hooks.slack.com/services/$2" # integrate with external APIs
```
