### ISSUE TITLE
Error when using Movefile

### ISSUE THREAD

**Issue by charmcat** [welaika/wordmove#150]
```
/home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:29:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/bin/wordmove:23:in `load'
	from /home/vagrant/.rbenv/versions/1.9.3-p551/bin/wordmove:23:in `<main>'
```

**Comment by pioneerskies** [comment]
Hello @charmcat ,

in order to help we need to have 1) the command you launched 2) your Movefile (remove sensible data from it before to post)

Thanks in advance

**Comment by charmcat** [comment]
The command was "wordmove pull -e live --all". Here's the redacted Movefile:

```
local:
  vhost: "localhost"
  wordpress_path: "/Users/ashleighsmith/Sites/charmcat-local/html" # use an absolute path here

  database:
    name: "wordpress"
    user: "root"
    password: "root"
    host: "127.0.0.1"

staging:
  vhost: "http://dev.charmcat.net"
  wordpress_path: "/dev/www" # use an absolute path here

  database:
    name: "--name--"
    user: "--user--"
    password: "--password--"
    host: "--host--"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  ftp:
    user: "--user--"
    password: "--password--"
    host: "--host--"

live:
  vhost: "http://www.charmcat.net"
  wordpress_path: "/charmcat/www/" # use an absolute path here

  database:
    name: "--name--"
    user: "--user--"
    password: "--password--"
    host: "--host--"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  ftp:
    user: "--user--"
    password: "--password--"
    host: "--host--"
```
