### ISSUE TITLE
wp-options "siteurl" and "home" not changed on pull command

### ISSUE THREAD

**Issue by sulram** [welaika/wordmove#160]
hello! thanks for this wonderful script

sometimes "siteurl" and "home" options are not changed on pull command.

is that related to websites that vhost is not a domain, when it resides inside a directory?

best,

Marlus

**Comment by tjaadvd** [comment]
I have seen this behavior also recently. Could it be due to a new version of Wordpress?

**Comment by pioneerskies** [comment]
Well, guys, we're very thankful for you issues, but in order to make them 100% useful we'd need some scientific details or we won't be able to make a troubleshoot.
For example: what the two values are in the database in both local and remote environment before and after the substitution? what is the WP version? And so on...

As it stands we're totally blind. Thank you very much for any effort you'll put in! :)

**Comment by AlphaBlossom** [comment]
Hello,

Thanks for the great script! I've recently started using wordmove and over the last few weeks have come across the same issue as above.

I'm using vvv, and when I set up a site, mysite.dev and pull all from mysite.com, the homepage works, but all links remove mysite.com.

Looking in the _options table shows mysite.com has not been updated to mysite.com (as well as all locations in the db - search and replace required for all).

Here is my wordmove file:

```
local:
  vhost: "http://localsitename.dev"
  wordpress_path: "/vagrant/www/localsitename/htdocs" # use an absolute path here

  database:
    name: "localsitename"
    user: "localdbuser"
    password: "localdbpw"
    host: "127.0.0.1"

production:
  vhost: "http://11.11.11.1"
  wordpress_path: "/absolute/path/to/site" # use an absolute path here

  database:
    name: "productiondbname"
    user: "productiondbuser"
    password: "productiondbpw"
    host: "productionhostname"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  ssh:
    host: "11.11.11.1"
    user: "sshuser"
  #  password: "xxxxxx" # password is optional, will use public keys if available.
    port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true

# production: # multiple environments can be specified
#   [...]
```

I can't say the exact version of WP, but fairly recent like 4.2.3 and 4.2.4.

I haven't been using wm for long, but I didn't have this problem on the earlier sites that I pulled.
