### ISSUE TITLE
Error when pushing or pulling (same error)

### ISSUE THREAD

**Issue by baldiri** [welaika/wordmove#176]
Hi, 
at first place let me tell you that is a fantastic job what are you doing for community, Thanks a lot!!!

My problem is that i always get same problem when try to pull or push:

```bash
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:25:in `deployer_for': You need to specify an environment with --environment parameter (RuntimeError)
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:45:in `pull'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

Here is my Movefile as well:

```yaml
  local:
    vhost: "http://camping_plana.dev"
    wordpress_path: "/srv/www/campinglaplana.com" # use an absolute path here

  database:
    name: "???????"
    user: "???????"
    password: "???????"
    host: "localhost"

  staging:
    vhost: "http://www.campinglaplana.com"
    wordpress_path: "/var/www/vhosts/campinglaplana.com/httpdocs" # use an absolute path here

  database:
    name: "???????"
    user: "???????"
    password: "???????"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

   ftp:
     user: "???????"
     password: "???????"
     host: "www.campinglaplana.com"
     passive: true

# production: # multiple environments can be specified
#   [...]
```

Any ideas¿?, i'm working from a vagrant box, vvv following your wiki instructions.

**Comment by pioneerskies** [comment]
Hi @baldiri ,

I think you're having some problems with the YAML's indentation. You need a lot of attention around it. Try w/ this version:

```yaml
local:
  vhost: "http://camping_plana.dev"
  wordpress_path: "/srv/www/campinglaplana.com" # use an absolute path here

  database:
    name: "???????"
    user: "???????"
    password: "???????"
    host: "localhost"

staging:
  vhost: "http://www.campinglaplana.com"
  wordpress_path: "/var/www/vhosts/campinglaplana.com/httpdocs" # use an absolute path here

  database:
    name: "???????"
    user: "???????"
    password: "???????"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "???????"
    password: "???????"
    host: "www.campinglaplana.com"
    passive: true

# production: # multiple environments can be specified
#   [...]
```
