### ISSUE TITLE
Error while pushing or pulling wordmove

### ISSUE THREAD

**Issue by geetpurwar** [welaika/wordmove#182]
hi,

Local server: MAMP/ 8888 port
Staging server: Digital Ocean with ubuntu 14/ wordpress installed
Here's my movefile:

	local:
	vhost: "http://localhost:8888/fsf"
	wordpress_path: "/Applications/MAMP/htdocs/fsf" # use an absolute path here

	database:
	name: "fsf"
	user: "root"
	password: "root"
	host: "localhost"

	staging:
	vhost: "http://45.55.84.91/"
	wordpress_path: "/var/www/html" # use an absolute path here

	database:
	name: "wordpress"
	user: "wordpress"
	password: "password"
	host: "localhost"
	# port: "3308" # Use just in case you have exotic server config

	exclude:
	- ".git/"
	- ".gitignore"
	- ".sass-cache/"
	- "bin/"
	- "tmp/*"
	- "Gemfile*"
	- "Movefile"
	- "wp-config.php"
	- "wp-content/*.sql"

	# paths: # you can customize wordpress internal paths
	#   wp_content: "wp-content"
	#   uploads: "wp-content/uploads"
	#   plugins: "wp-content/plugins"
	#   themes: "wp-content/themes"
	#   languages: "wp-content/languages"
	#   themes: "wp-content/themes"

	ssh:
	   host: "http://45.55.84.91"
	   user: "root"
	   password: "password"
	#  port: 22 # Port is optional
	#   rsync_options: "--verbose" # Additional rsync options, optional
	#   gateway: # Gateway is optional
	#     host: "host"
	#     user: "user"
	#     password: "password" # password is optional, will use public keys if available.

	# ftp:
	#   user: "user"
	#   password: "password"
	#   host: "host"
	#   passive: true

	# production: # multiple environments can be specified
	#   [...]

Here's the error, I am getting either while push or pull:

	▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
	/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:29:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
		from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
		from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
		from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
		from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
		from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
		from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
		from /usr/bin/wordmove:23:in `load'
		from /usr/bin/wordmove:23:in `<main>'

Screenshot of error: http://grab.by/IDGU
<img width="1440" alt="screen shot 2015-07-08 at 1 23 26 am" src="https://cloud.githubusercontent.com/assets/1036139/8555830/4329417c-2510-11e5-82d9-755420d3f8c7.png">

Please let me know how can I fix it.
Thanks.

**Comment by pioneerskies** [comment]
Hi @geetpurwar ,

as you can notice by yourself your `Movefile` has no indentations at all.

Please, keep the one from our README and consider that YAML format is indentation sensitive; based on this reorder your `Movefile`, try again and tell us the news.

If it will start working remember to close the issue :)

Cheers

**Comment by pioneerskies** [comment]
Probably it should be

```yaml
local:
  vhost: "http://localhost:8888/fsf"
  wordpress_path: "/Applications/MAMP/htdocs/fsf" # use an absolute path here

  database:
    name: "fsf"
    user: "root"
    password: "root"
    host: "localhost"

staging:
  vhost: "http://45.55.84.91/"
  wordpress_path: "/var/www/html" # use an absolute path here

  database:
    name: "wordpress"
    user: "wordpress"
    password: "password"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  ssh:
    host: "http://45.55.84.91"
    user: "root"
    password: "password"
    
```
