### ISSUE TITLE
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect

### ISSUE THREAD

**Issue by rwbrown72** [welaika/wordmove#193]
<h1>Hello..</h1> and thanks for a cool gem. 

I'm testing out this gem and I'm having an issue with the dump.sql.  I'm going to delete this test server as soon as I'm finished writing this. 

Here is the error I'm getting: 

```bash
Russells-iMac:jjlaw Home$ wordmove push --all -e live

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/jjlaw /var/www/html/jjlaw .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-07-27T13:46:35.031210 #52357]  INFO -- : rsync --progress -e 'ssh root@###.###.##.###' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Applications/MAMP/htdocs/jjlaw/ :/var/www/html/jjlaw
building file list ... 
1096 files to consider

sent 22137 bytes  received 20 bytes  14771.33 bytes/sec
total size is 16314178  speedup is 736.30

▬▬ ✓ Pushing Uploads ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/jjlaw/wp-content/uploads /var/www/html/jjlaw/wp-content/uploads .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-07-27T13:46:36.439542 #52357]  INFO -- : rsync --progress -e 'ssh root@###.###.##.###' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Applications/MAMP/htdocs/jjlaw/wp-content/uploads/ :/var/www/html/jjlaw/wp-content/uploads
building file list ... 
rsync: link_stat "/Applications/MAMP/htdocs/jjlaw/wp-content/uploads/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  132.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/jjlaw/wp-content/themes /var/www/html/jjlaw/wp-content/themes .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-07-27T13:46:37.613782 #52357]  INFO -- : rsync --progress -e 'ssh root@###.###.##.###-rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Applications/MAMP/htdocs/jjlaw/wp-content/themes/ :/var/www/html/jjlaw/wp-content/themes
building file list ... 
255 files to consider

sent 5688 bytes  received 20 bytes  3805.33 bytes/sec
total size is 3586162  speedup is 628.27

▬▬ ✓ Pushing Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/jjlaw/wp-content/plugins /var/www/html/jjlaw/wp-content/plugins .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-07-27T13:46:38.757478 #52357]  INFO -- : rsync --progress -e 'ssh root@###.###.##.###' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Applications/MAMP/htdocs/jjlaw/wp-content/plugins/ :/var/www/html/jjlaw/wp-content/plugins
building file list ... 
25 files to consider

sent 699 bytes  received 20 bytes  479.33 bytes/sec
total size is 148520  speedup is 206.56

▬▬ ✓ Pushing Languages ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/jjlaw/wp-content/languages /var/www/html/jjlaw/wp-content/languages .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-07-27T13:46:39.847951 #52357]  INFO -- : rsync --progress -e 'ssh root@###.###.##.###' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Applications/MAMP/htdocs/jjlaw/wp-content/languages/ :/var/www/html/jjlaw/wp-content/languages
building file list ... 
rsync: link_stat "/Applications/MAMP/htdocs/jjlaw/wp-content/languages/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  132.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=localhost --user=wordpress --password=######### wordpress > /var/www/html/jjlaw/wp-content/dump.sql
   remote | get: /var/www/html/jjlaw/wp-content/dump.sql /Applications/MAMP/htdocs/jjlaw/wp-content/live-backup-1438022801.sql
   remote | delete: /var/www/html/jjlaw/wp-content/dump.sql
    local | mysqldump --host=127.0.0.1 --user=root --password=root jjlaw > /Applications/MAMP/htdocs/jjlaw/wp-content/dump.sql
Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
/Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:147:in `run': Return code reports an error (RuntimeError)
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:210:in `save_local_db'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:20:in `push_db'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/Home/.rvm/gems/ruby-2.1.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /Users/Home/.rvm/gems/ruby-2.1.1/bin/wordmove:23:in `load'
	from /Users/Home/.rvm/gems/ruby-2.1.1/bin/wordmove:23:in `<main>'
	from /Users/Home/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Home/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

<hr>
There seems to be an issue with the Database Dump. It's creating backup files, but it's not outputting anything to the server. I'll add an image of the backup files being created below. 

![dump](https://cloud.githubusercontent.com/assets/6172865/8914891/588b289e-3467-11e5-8eee-13a007f1cfbd.png)

Lastly, here is my move file: 

```yaml
local:
  vhost: "http://localhost:8888/jjlaw"
  wordpress_path: "/Applications/MAMP/htdocs/jjlaw" # use an absolute path here

  database:
    name: "jjlaw"
    user: "root"
    password: "root"
    host: "127.0.0.1"

live:
  vhost: "http://###.###.##.###"
  wordpress_path: "/var/www/html/jjlaw" # use an absolute path here

  database:
    name: "wordpress"
    user: "wordpress"
    password: "##########"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  ssh:
    host: "###.###.##.###"
    user: "root"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

```

As far as I can tell, my passwords are correct and I don't have any indention errors on the page.  The ssh is working fine for both temial ssh as well as using an FTP client. I cannot get past the mySql 1045 error and thought you guys might have some idea to help. Thanks again for the efforts on the gem.  

All the best,

Russell Brown
<a href="https://twitter.com/russellbrownco">@russellbrownco</a>
