### ISSUE TITLE
mkdir: Access failed: 550 Can't create directory: No such file or directory

### ISSUE THREAD

**Issue by afmarchetti** [welaika/wordmove#201]
Hi! Wordmove is awesome thank You! 
I have this problem, when i launch the command: wordmove push --all -e staging
i have this error:

mkdir: Access failed: 550 Can't create directory: No such file or directory (/web/htdocs/test.marchettidesign.net/home)
cd: Access failed: 550 Can't change directory to web: No such file or directory (/web/htdocs/test.marchettidesign.net/home)
Transferring file `.DS_Store'                              
Transferring file `Movefile'
mirror: Access failed: 553 Can't open that file: Permission denied (.DS_Store)
Transferring file `index.php'

after this all the file that lftp try to upload return this error (for all the files in local directory):

rm: Access failed: 550 Could not delete admin.php: Read-only file system

I have to set my permission file in differt way?
This is my move file:

```yaml
local:
  vhost: "http://XXXXX/lab/"
  wordpress_path: "/Applications/XAMPP/xamppfiles/htdocs/lab" # use an absolute path here

  database:
    name: "XXXXX"
    user: "root"
    password: ""
    host: "localhost"

staging:
  vhost: "http://test.marchettidesign.net/"
  wordpress_path: "/web/htdocs/test.marchettidesign.net/home" # use an absolute path here

  database:
    name: "XXXX"
    user: "XXXX"
    password: "XXXXX"
    host: "XXXX"
  
  ftp:
    user: "XXXX"
    password: "XXXX"
    host: "ftp.test.marchettidesign.net"
    passive: true   


exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
```
