### ISSUE TITLE
Wordmove::ShellCommandError

### ISSUE THREAD

**Issue by RaMonkey** [welaika/wordmove#215]
```bash
▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /domains/blblabla.com/public_html/test-lab/wp-content/dump.php
    local | download http://blablabla.com/test-lab/wp-content/dump.php?shared_key=95370a688e3320879807a2898c7d7f2feadf78e30e166f6bfa336564689f6ef4964bf19e4ff6edc8 > /Users/ramon/Sites/WP-SITES/test-lab/wp-content/remote-backup-1441782106.sql
   remote | delete: /domains/blablabla.com/public_html/test-lab/wp-content/dump.php
mysqldump --host=localhost --user=xxxx --password=xxxxxxxx test-lab --result-file=/Users/ramon/Sites/WP-SITES/test-lab/wp-content/dump.sql
    local | mysqldump --host=localhost --user=xxxx --password=xxxxxxxx test-lab --result-file=/Users/ramon/Sites/WP-SITES/test-lab/wp-content/dump.sql
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:208:in `save_local_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:19:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

Push/Pull files work fine but can't get the DB Pushed nor Pulled.

Using Mamp locally.

```yml
local: 
  database: 
    host: "localhost"
    name: test-lab
    password: ********
    user: ****
  vhost: "http://localhost:8888/test-lab"
  wordpress_path: /Users/ramon/Sites/WP-SITES/test-lab
production: 
  database: 
    host: localhost
    name: *******-lab
    password: ********
    user: ************
  exclude: 
    - .git/
    - .gitignore
    - .sass-cache/
    - node_modules/
    - bin/
    - tmp/*
    - Gemfile*
    - Movefile
    - wp-config.php
    - wp-content/*.sql
    - scss/
  ftp: 
    host: blablabla.com
    password: ********
    user: ********
  vhost: "http://blablabla.com/test-lab"
  wordpress_path: /domains/blablabla.com/public_html/test-lab
```
