### ISSUE TITLE
Parse error - changing WP-content path not working correctly. 

### ISSUE THREAD

**Issue by dsgnr** [welaika/wordmove#242]
Hello, 
I have recently come across Wordmove and it looks fantastic - exactly what I need! However, I am having a few issues getting it working. I have successfully installed Ruby and Wordmove (OSX El Capitan) and I can init a Wordmove file which I have entered below... But when trying to push or pull, I am getting an error.

Here is my Wordmove file:
````
local:
  vhost: "http://local.domain.dev”
  wordpress_path: “/users/name/Documents/test" # use an absolute path here

  database:
    name: "test1"
    user: "root"
    password: "root"
    host: "localhost:8888”

staging:
  vhost: "http://domain.com hidden for this post”
  wordpress_path: “/home/directory/public_html” # use an absolute path here

  database:
    name: “test1”
    user: “root”
    password: "root"
    host: “localhost”
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
      host: “omitted for this post”
      user: “omitted for this post”
  #   password: "omitted for this post" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true

# production: # multiple environments can be specified
#   [...]`
````

Here is the error I am getting:

     ▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 6 column 5 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:47:in `fetch_movefile'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:11:in `deployer_for'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:58:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'`

I'd love to get this working.

I get this issue in both Vagrant and MAMP Pro if this makes a difference. It looks like an error with the Wordmove file but I can't see anything wrong with it

*Edit: Added proper markdown for easier reading of Wordmove File.
