### ISSUE TITLE
wordmove doesn't do anything...

### ISSUE THREAD

**Issue by bambamboole** [welaika/wordmove#248]
I just found this repo and was so happy because this gem does exactly what I need not more and not less...

but after wordmove init and customizing wordmove file i ran:

``wordmove push -e staging``

and the output is only
``
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
``

anybody knows what i am doing wrong?

**Comment by simonmacfadyen** [comment]
Do you have a staging environment defined? Post your Movefile.

**Comment by bambamboole** [comment]
local:
  vhost: "http://local.dev"
  wordpress_path: "/local/path/to/my/wordpress" # use an absolute path here

  database:
    name: "localDbName"
    user: "root"
    password: ""
    host: "127.0.0.1"

staging:
  vhost: "http://remote.com"
  wordpress_path: "/remote/path/to/my/wordpress" # use an absolute path here

  database:
    name: "remoteDbName"
    user: "user"
    password: "pw"
    host: "mysql5.remote.com"

  exclude:
    - "wp-config.php"


  ssh:
    host: "remote.com"
    user: "ssh-user"
    password: sshPassword # password is optional, will use public keys if available.
    port: 22 # Port is optional
    rsync_options: "--verbose" # Additional rsync options, optional

**Comment by bambamboole** [comment]
```
local:
  vhost: "http://local.dev"
  wordpress_path: "/local/path/to/my/wordpress" # use an absolute path here

  database:
    name: "localDbName"
    user: "root"
    password: ""
    host: "127.0.0.1"

production:
  vhost: "http://remote.com"
  wordpress_path: "/remote/path/to/my/wordpress" # use an absolute path here

  database:
    name: "remoteDbName"
    user: "user"
    password: "pw"
    host: "mysql5.remote.com"

  exclude:
    - "wp-config.php"


  ssh:
    host: "remote.com"
    user: "ssh-user"
    password: sshPassword # password is optional, will use public keys if available.
    port: 22 # Port is optional
    rsync_options: "--verbose" # Additional rsync options, optional
```
