### ISSUE TITLE
"wordmove pull -d" does not sync with local db

### ISSUE THREAD

**Issue by joshuatomasgarcia** [welaika/wordmove#251]
Running VVV and wordmove will not sync the remote with the local db. 
Tried to update but when I run 
`$sudo gem install wordmove --pre`
I get this 
`ERROR:  Error installing wordmove:`
`    wordmove requires Ruby version ~> 2.0.` 
(I get the same error with photocopy, as well) 
Despite this: 
`$ruby -v`
`     ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]`

I got wordmove 1.40.0.pre4 to install by modifying the provisioning script:
```
==> default: wordmove not installed
==> default: Successfully installed net-ssh-2.9.2
==> default: Successfully installed net-ssh-gateway-1.2.0
==> default: Successfully installed net-scp-1.2.1
==> default: Successfully installed thread_safe-0.3.5
==> default: Successfully installed tzinfo-1.2.2
==> default: Successfully installed i18n-0.7.0
==> default: Successfully installed activesupport-4.2.5
==> default: Successfully installed photocopier-1.0.0
==> default: Successfully installed thor-0.19.1
==> default: Successfully installed colorize-0.7.7
==> default:     Starting from 1.4.0 Wordmove will compress SQL dumps both in remote and locale environments.
==> default:     If something will broke, please check if gzip and gunzip executables are present locally and
==> default:     remotely. We are considering obviuos they are installed in any web environment.
==> default:     Open an issue on github at your needs.
==> default: Successfully installed wordmove-1.4.0.pre4
==> default: Parsing documentation for net-ssh-2.9.2
==> default: Installing ri documentation for net-ssh-2.9.2
==> default: Parsing documentation for net-ssh-gateway-1.2.0
==> default: Installing ri documentation for net-ssh-gateway-1.2.0
==> default: Parsing documentation for net-scp-1.2.1
==> default: Installing ri documentation for net-scp-1.2.1
==> default: Parsing documentation for thread_safe-0.3.5
==> default: Installing ri documentation for thread_safe-0.3.5
==> default: Parsing documentation for tzinfo-1.2.2
==> default: Installing ri documentation for tzinfo-1.2.2
==> default: Parsing documentation for i18n-0.7.0
==> default: Installing ri documentation for i18n-0.7.0
==> default: Parsing documentation for activesupport-4.2.5
==> default: Installing ri documentation for activesupport-4.2.5
==> default: Parsing documentation for photocopier-1.0.0
==> default: Installing ri documentation for photocopier-1.0.0
==> default: Parsing documentation for thor-0.19.1
==> default: Installing ri documentation for thor-0.19.1
==> default: Parsing documentation for colorize-0.7.7
==> default: Installing ri documentation for colorize-0.7.7
==> default: Parsing documentation for wordmove-1.4.0.pre4
==> default: Installing ri documentation for wordmove-1.4.0.pre4
==> default: Done installing documentation for net-ssh, net-ssh-gateway, net-scp, thread_safe, tzinfo, i18n, activesupport, photocopier, thor, colorize, wordmove after 9 seconds
==> default: 11 gems installed
==> default: can require yams
``` 

The Movefile seems to be working otherwise and is dumping the db, I can see the correct database.mysql file on the server (wp-content/dump.mysql). It however does not sync that remote file to the local server. 

I tried installing it on OS X and using the absolute path in my OS X filesystem, but got this:
```
`$wordmove pull -d `
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=wp --password=wp --result-file=/Users/joshuagarcia/11Online/Tools/Development/vagrant-local/www/11online.us/wp-content/local-backup-1450424249.sql 11online.us
    local | mysqldump --host=localhost --user=wp --password=wp --result-file=/Users/joshuagarcia/11Online/Tools/Development/vagrant-local/www/11online.us/wp-content/local-backup-1450424249.sql 11online.us
/usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/base.rb:141:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/base.rb:230:in `save_local_db'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/ftp.rb:39:in `pull_db'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:59:in `block in pull'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:35:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:35:in `handle_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:58:in `pull'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```
Which seemed almost predictable based on what other people were reporting in other issues. Word move 1.3.1 seems to install fine using the documentation on how to get it to install in VVV but does not sync the database. I thought updating would help since I saw this issue (but it didn't seem to): https://github.com/welaika/wordmove/issues/210

I did not see any compressed SQL dumps in either remote and local environments. 

Please advise. 

Here is the output I get that does not sync with the database:
```
vagrant@vvv:/srv/www/11online.us$ which wordmove
/usr/local/rvm/gems/ruby-2.2.1/bin/wordmove
vagrant@vvv:/srv/www/11online.us$ wordmove pull -d -v

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=wp --password=wp --result-file=/srv/www/11online.us/htdocs/wp-content/local-backup-1450425986.sql 11online.us
    local | mysqldump --host=localhost --user=wp --password=wp --result-file=/srv/www/11online.us/htdocs/wp-content/local-backup-1450425986.sql 11online.us
   remote | write /public_html/11online.us/wp-content/dump.php
    local | download http://11online.us/wp-content/dump.php?shared_key=5bbbbd22bb86db7fcd257ac423aaaf6b8edf6cd14963fc39758ad010d09ebb47529c9caf9185aa75 > /srv/www/11online.us/htdocs/wp-content/dump.sql
   remote | delete: /public_html/11online.us/wp-content/dump.php
    local | adapt dump
mysql --host=localhost --user=wp --password=wp --database=11online.us --execute=SOURCE\ /srv/www/11online.us/htdocs/wp-content/dump.sql
    local | mysql --host=localhost --user=wp --password=wp --database=11online.us --execute=SOURCE\ /srv/www/11online.us/htdocs/wp-content/dump.sql
    local | rm /srv/www/11online.us/htdocs/wp-content/dump.sql
```

And here is my move file:
```
local:
  vhost: "http://11online.us.dev"
  wordpress_path: "/srv/www/11online.us/htdocs" # use an absolute path here

  database:
    name: "11online.us"
    user: "wp"
    password: "wp"
    host: "localhost"

production:
  vhost: "http://11online.us"
  wordpress_path: "/public_html/11online.us" #relative FTP path
  wordpress_absolute_path: "/home/elevenon/public_html/11online.us" #absolute FTP path

  database:
    name: "elevenon_11onlin"
    user: "elevenon_11onlin"
    password: "***********"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "***********"
    password: "***********"
    host: "***********"
    passive: true

# production: # multiple environments can be specified
#   [...]

```

**Comment by joshuatomasgarcia** [comment]
I am basically having the same problem this person is (different gem, of course but sudo is the culprit): https://github.com/jekyll/jekyll/issues/3558 

But if I run 
`gem install wordmove --pre`
I get a permissions error in Vagrant. 

I tried installing it on OS X and using the absolute path in my OS X filesystem, but got this:
```
`$wordmove pull -d `
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=wp --password=wp --result-file=/Users/joshuagarcia/11Online/Tools/Development/vagrant-local/www/11online.us/wp-content/local-backup-1450424249.sql 11online.us
    local | mysqldump --host=localhost --user=wp --password=wp --result-file=/Users/joshuagarcia/11Online/Tools/Development/vagrant-local/www/11online.us/wp-content/local-backup-1450424249.sql 11online.us
/usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/base.rb:141:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/base.rb:230:in `save_local_db'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/deployer/ftp.rb:39:in `pull_db'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:59:in `block in pull'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:35:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:35:in `handle_options'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/lib/wordmove/cli.rb:58:in `pull'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/wordmove-1.4.0.pre4/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```
Which seemed almost predictable based on what other people were reporting in other issues. Word move 1.3.1 seems to install fine using the documentation on how to get it to install in VVV but does not sync the database. I thought updating would help since I saw this issue (but perhaps not): https://github.com/welaika/wordmove/issues/210

**Comment by joshuatomasgarcia** [comment]
By the way, here is my move file just in case:
```
local:
  vhost: "http://11online.us.dev"
  wordpress_path: "/srv/www/11online.us/htdocs" # use an absolute path here

  database:
    name: "11online.us"
    user: "wp"
    password: "wp"
    host: "localhost"

production:
  vhost: "http://11online.us"
  wordpress_path: "/public_html/11online.us" #relative FTP path
  wordpress_absolute_path: "/home/elevenon/public_html/11online.us" #absolute FTP path

  database:
    name: "elevenon_11onlin"
    user: "elevenon_11onlin"
    password: "***********"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: "***********"
    password: "***********"
    host: "***********"
    passive: true

# production: # multiple environments can be specified
#   [...]

```
