### ISSUE TITLE
Database pull always returns empty dump.sql

### ISSUE THREAD

**Issue by rotexhawk** [welaika/wordmove#291]
When I do a database pull request everything passes but no value is changed on my local database. I stopped wordmove script before deleting the dump files and noticed that the dump file on the server is correct but the one on the local machine is empty. So, for some reason wordmove is downloading empty file. Not sure if this is the actual problem, just wanted to report my own findings. 

Tried with sudo and the got the same results. I am using Siteground for production.
 
Operating System - OSX - El-Capitan
Ruby - ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
Wordmove Version - 1.3.1
Using System Ruby.
```
local:
  vhost: "http://localhost/~macintosh"
  wordpress_path: "/Users/macintosh/Sites/oldpeak" # use an absolute path here

  database:
    name: "oldpeak"
    user: "username"
    password: "password"
    host: "127.0.0.1"

production:
  vhost: "http://181.224.138.173/~food9349/oldpeak"
  wordpress_path: "/oldpeak" # use an absolute path here

  database:
    name: "dbname"
    user: "username"
    password: "password"
    host: "127.0.0.1"
    # port: "3308" # Use just in case you have exotic server config

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"
    - ".htaccess"
    - ".DS_Store"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"
  #   themes: "wp-content/themes"

  #ssh:
  #    host: "127.0.0.1"
  #    user: "paulbarth"
  #    password: "Copper1998"
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
      user: "rotexhawk@oldpeakfinance.com"
      password: "password"
      host: "181.224.138.173"
  #   passive: true
```
