### ISSUE TITLE
wordmove non mi funziona chiedo aiuto 

### ISSUE THREAD

**Issue by mariello124** [welaika/wordmove#314]
ho provato WordMove su linux usando XAMPP il traferimento via ftp:

installato Ruby facendo

```
apt-get install ruby
```

poi installato wordmove:

```
gem install wordmove
```

poi verificato installazione :wordmove

```
Commands:
wordmove –version, -v # Print the version
wordmove help [COMMAND] # Describe available commands or one specific command
wordmove init # Generates a brand new Movefile
wordmove pull # Pulls WP data from remote host to the local machine
wordmove push # Pushes WP data from local machine to remote host
```

poi creato il file per il trasferimento Movefile:

```
wordmove init
```

aperto con Gedit e modificato Movefile coi Parametri hosting salvato e lanciato il pull ma mi da questi errori

```
wordmove pull –all
```

``` bash
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/lib/ruby/2.3.0/psych.rb:377:in `parse’: (<unknown>): did not find expected key while parsing a block mapping at line 13 column 3 (Psych::SyntaxError)
from /usr/lib/ruby/2.3.0/psych.rb:377:in `parse_stream’
from /usr/lib/ruby/2.3.0/psych.rb:325:in `parse’
from /usr/lib/ruby/2.3.0/psych.rb:252:in `load’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:42:in `fetch_movefile’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:10:in `deployer_for’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:63:in `pull’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>’
from /usr/local/bin/wordmove:23:in `load’
from /usr/local/bin/wordmove:23:in `<main>’
```

Mi sapreste Aiutare Grazie
Giancarlo Piccinini
scusate se ho scritto 2 volte prima volta che uso gitub

**Comment by pioneerskies** [comment]
As far as I am a native Italian speaker I will follow up on this issue in Italian. Sorry to other community members who will not understand a single word :P

Ciao @mariello124 ,

per il futuro mi raccomando alcune cose:
* seguire queste istruzioni per la compilazione delle issue su github: https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting
* cercare di usare l'inglese come lingua di comunicazione, anche brutto: lo capiremo in qualche modo :)
* imparare ad usare il markdown e formattare bene i testi e' fondamentale ;)

Detto cio': il tuo e' un problema con il `Movefile`, nel quale o manca una chiave di configurazione o piu' semplicemente e' formattata male (negli YAML l'indentazione deve essere esatta).

Ci puoi incollare il tuo `Movefile` ripulito dai dati sensibili? Grazie

**Comment by mariello124** [comment]
Da: "Alessandro Fazzi" notifications@github.com
A: "welaika/wordmove" wordmove@noreply.github.com
Cc: "mariello124" giancarlo@giangi.it,"Mention" mention@noreply.github.com
Data: Mon, 30 May 2016 00:46:10 -0700
Oggetto: Re: [welaika/wordmove] wordmove non mi funziona chiedo aiuto  (#314)


As far as I am a native Italian speaker I will follow up on this issue in Italian. Sorry to other community members who will not understand a single word :P

Ciao @mariello124 ,

per il futuro mi raccomando alcune cose:


seguire queste istruzioni per la compilazione delle issue su github: https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting

cercare di usare l'inglese come lingua di comunicazione, anche brutto: lo capiremo in qualche modo :)
imparare ad usare il markdown e formattare bene i testi e' fondamentale ;)

Grazie della Risposta 
inglese lo so poco Purtroppo 
ho provato a fare il tutto via FTP  


Giancarlo Piccinini
Email: giancarlo@giangi.it
Tel. Fax 059527349

 


Detto cio': il tuo e' un problema con il Movefile, nel quale o manca una chiave di configurazione o piu' semplicemente e' formattata male (negli YAML l'indentazione deve essere esatta).

Ci puoi incollare il tuo Movefile ripulito dai dati sensibili? Grazie

**Comment by pioneerskies** [comment]
Ci puoi incollare il tuo Movefile ripulito dai dati sensibili? Grazie

**Comment by mariello124** [comment]
ok come dicevo email -Precedenti Siete Gentilissimi allego il mio File Movefile 
RIEPILOGO I MIEI PROBLEMI :::

—-ho provato WordMove su linux usando XAMPP il trasferimento via ftp:
—-installato Ruby facendo
# apt-get install ruby
—-poi installato wordmove:
gem install wordmove
—-poi verificato installazione :
# wordmove
Commands:
wordmove –version, -v # Print the version
wordmove help [COMMAND] # Describe available commands or one specific command
wordmove init # Generates a brand new Movefile
wordmove pull # Pulls WP data from remote host to the local machine
wordmove push # Pushes WP data from local machine to remote host
—- poi creato il file per il trasferimento Movefile:
wordmove init
—-aperto con Gedit e modificato Movefile coi Parametri hosting salvato e lanciato il pull ma mi da questi errori# wordmove pull –all▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/lib/ruby/2.3.0/psych.rb:377:in `parse’: (<unknown>): did not find expected key while parsing a block mapping at line 13 column 3 (Psych::SyntaxError)
from /usr/lib/ruby/2.3.0/psych.rb:377:in `parse_stream’
from /usr/lib/ruby/2.3.0/psych.rb:325:in `parse’
from /usr/lib/ruby/2.3.0/psych.rb:252:in `load’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:42:in `fetch_movefile’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:10:in `deployer_for’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:63:in `pull’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch’
from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start’
from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>’
from /usr/local/bin/wordmove:23:in `load’
from /usr/local/bin/wordmove:23:in `<main>’ 
 
 

Giancarlo Piccinini
Email: giancarlo@giangi.it
Tel. Fax 059527349
Skype  = giangiit


Da: "Alessandro Fazzi" notifications@github.com
A: "welaika/wordmove" wordmove@noreply.github.com
Cc: "mariello124" giancarlo@giangi.it,"Mention" mention@noreply.github.com
Data: Mon, 30 May 2016 06:46:14 -0700
Oggetto: Re: [welaika/wordmove] wordmove non mi funziona chiedo aiuto  (#314)


Ci puoi incollare il tuo Movefile ripulito dai dati sensibili? Grazie

**Comment by pioneerskies** [comment]
Mi dispiace, ma non son in grado di aiutarti perche' non verifichiamo il comportamento con setup simili e perche' non fornisci le informazioni richieste.

Assicurati ti aver letto al meglio la documentazione del wiki qui su github.

**Comment by mariello124** [comment]
I did not understand what was going
under my Move files
------------------------------------------------
local:
  vhost: "http://localhost"
  wordpress_path: "/opt/lampp/htdocs/nuova" # use an absolute path here

  database:
    name: "nuova"
    user: "root"
    password: ""
    host: "127.0.0.1"


production:
  vhost: "http://www.giangi.it"
  wordpress_path: "/web/htdocs/www.giangi.it/home/kyo" # use an absolute path here

  database:
    name: "Sql******_3"
    user: "Sql******"
    password: "********"
    host: "11.111.111.111"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
   - ".git/"
   - ".gitignore"
  - ".sass-cache/"
  - "node_modules/"
  - "bin/"
  - "tmp/*"
  - "Gemfile*"
  - "Movefile"
  - "wp-config.php"
  - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

 ftp:
 user: "*******@aruba.it"
 password: "*********"
 host: "ftp.giangi.it"
 passive: true
# scheme: "ftps" 
default "ftp"

# staging: # multiple environments can be specified
#   [...]

**Comment by mariello124** [comment]
scusate non ho capito cosa non andava 
 ho messo il movefile alla discussione https://github.com/welaika/wordmove/issues/314

non ho mai usato https://github.com
 
Grazie  

Giancarlo Piccinini
Email: giancarlo@giangi.it
Tel. Fax 059527349
Skype  = giangiit


Da: "Alessandro Fazzi" notifications@github.com
A: "welaika/wordmove" wordmove@noreply.github.com
Cc: "mariello124" giancarlo@giangi.it,"Mention" mention@noreply.github.com
Data: Tue, 31 May 2016 06:29:11 -0700
Oggetto: Re: [welaika/wordmove] wordmove non mi funziona chiedo aiuto  (#314)


Closed #314.

**Comment by endorama** [comment]
Ciao @mariello124, guardando il tuo Movefile pare che ci sia un problema di indentazione.

La sintassi con cui è scritto il Movefile si chiama YAML, ed è una sintassi sensibile all'indentazione. Il tuo Movefile ha molti problemi, e per questo ottenevi quell'errore. Ti consiglio di usare uno strumento come http://www.yamllint.com/ per verificarne la correttezza.

Inoltre, dovresti eliminare meglio le informazioni personali dal Movefile: sia i dati riguardanti il database che quelli dell'ftp sono molto espliciti per chi conosce il tuo hosting, e questa non è una buona cosa. Le prossime volte svuota completamente i campi sensibili.

Prova a copiare e incollare nel Movefile il testo qui sotto, compilando i campi necessari:
```yaml
local:
  vhost: "http://localhost"
  wordpress_path: "/opt/lampp/htdocs/nuova" # use an absolute path here

  database:
    name: "nuova"
    user: "root"
    password: ""
    host: "127.0.0.1"


production:
  vhost: "http://www.giangi.it"
  wordpress_path: "/web/htdocs/www.giangi.it/home/kyo" # use an absolute path here

  database:
    name: ""
    user: ""
    password: ""
    host: ""
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

    # paths: # you can customize wordpress internal paths
    #   wp_content: "wp-content"
    #   uploads: "wp-content/uploads"
    #   plugins: "wp-content/plugins"
    #   mu_plugins: "wp-content/mu-plugins"
    #   themes: "wp-content/themes"
    #   languages: "wp-content/languages"

    # ssh:
    #   host: "host"
    #   user: "user"
    #   password: "password" # password is optional, will use public keys if available.
    #   port: 22 # Port is optional
    #   rsync_options: "--verbose" # Additional rsync options, optional
    #   gateway: # Gateway is optional
    #     host: "host"
    #     user: "user"
    #     password: "password" # password is optional, will use public keys if available.

  ftp:
    user: ""
    password: ""
    host: ""
    passive: true
    # scheme: "ftps" default "ftp"

# staging: # multiple environments can be specified
#   [...]
```
