### ISSUE TITLE
Push can't write dump.sql Errcode2

### ISSUE THREAD

**Issue by wonderment** [welaika/wordmove#325]
Having issues here running this command:

`wordmove push -e staging -d`

which results in this:

> Error code 1 returned by command "mysqldump --host=internal-db.sXXXXXX.gridserver.com --user=wordpress_XXXXXX --password=XXXXXXXX --result-file="~/domains/XXXXXX.com/html/wp-content/dump.sql" dbXXXXXX_1clk_wordpress_BXJgBXmJK8xKTgxC": mysqldump: Can't create/write to file '~/domains/XXXXXX.com/html/wp-content/dump.sql' (Errcode: 2) (Wordmove::ShellCommandError)

Naturally, I replaced all sensitive details with X's.

I'm running VVV + VV. I have a public SSH key setup without a passphrase.

And, here's the Movefile:

```
local:
  vhost: "http://vhost.local"
  wordpress_path: "/srv/www/wordmove/htdocs" # use an absolute path here

  database:
    name: "wordmove"
    user: "wp"
    password: "wp"
    host: "localhost"

staging:
  vhost: "http://XXXXXX.com"
  wordpress_path: "~/domains/XXXXXX.com/html" # use an absolute path here

  database:
    name: "dbXXXXXX_1clk_wordpress_BXJgBXmJK8xKTgxC"
    user: "wordpress_XXXXXX"
    password: "XXXXXX"
    host: "internal-db.sXXXXXX.gridserver.com"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
     host: "sXXXXXX.gridserver.com"
     user: "XXXXXX.com"
  #   password: "xxxxxx" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]

```

Connecting to the remote server via SSH and running the following dumps the file into dump.sql perfectly fine:

`mysqldump -h internal-db.sXXXXXX.gridserver.com -u wordpress_XXXXXX -p XXXXXX dbXXXXXX_1clk_wordpress_BXJgBXmJK8xKTgxC > dump.sql`

The MediaTemple documentation utilizes the '>' operator as opposed to the '-result-file' option but I'm not sure if that has anything to do with it really.

This project is stuck in the mud until this is resolved, so I'd appreciate any assistance.

Thank you!
