### ISSUE TITLE
Pushing database runs with no errors but changes nothing

### ISSUE THREAD

**Issue by wonderment** [welaika/wordmove#326]
I ran the following inside the Vagrant machine (VVV) and it looks like everything processed normally but none of the database has changed on the remote server. It's a bare WordPress site and I simply created a post to test the database updates, but nothing is reflected.

```
vagrant@vvv:/srv/www/wordmove/htdocs$ wordmove push -e staging -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=internal-db.s000000.gridserver.com --user=wordpress_wordmove --password=00000000 --result-file="/home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql" db000000_1clk_wordpress_00000000000000000
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
wordmove.com@s000000.gridserver.com's password:XXXXXXXXXX!
gzip --best --force "/home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql"
   remote | gzip --best --force "/home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql"
   remote | get: /home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql.gz /srv/www/wordmove/htdocs/wp-content/staging-backup-1467776055.sql.gz
   remote | delete: /home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql.gz
    local | mysqldump --host=localhost --user=wp --password=wp --result-file="/srv/www/wordmove/htdocs/wp-content/dump.sql" wordmove
    local | adapt dump
gzip --best --force "/srv/www/wordmove/htdocs/wp-content/dump.sql"
    local | gzip --best --force "/srv/www/wordmove/htdocs/wp-content/dump.sql"
   remote | put: /srv/www/wordmove/htdocs/wp-content/dump.sql.gz /home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql.gz
gzip -d --force "/home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql.gz"
   remote | gzip -d --force "/home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql.gz"
   remote | mysql --host=internal-db.s000000.gridserver.com --user=wordpress_wordmove --password=00000000 --database=db000000_1clk_wordpress_00000000000000000 --execute="SET autocommit=0;SOURCE /home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql;COMMIT"
   remote | delete: /home/000000/users/.home/domains/wordmove.com/html/wp-content/dump.sql
    local | delete: '/srv/www/wordmove/htdocs/wp-content/dump.sql.gz'
```

Here's system info:

Ruby on vagrant machine: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
Wordmove on vagrant machine: 2.0.0
OS: OSX 10.11.5 (15F3)

And here's the Movefile:

```
local:
  vhost: "http://vhost.local"
  wordpress_path: "/srv/www/wordmove/htdocs" # use an absolute path here

  database:
    name: "wordmove"
    user: "wp"
    password: "wp"
    host: "localhost"

staging:
  vhost: "http://wordmove.com"
  wordpress_path: "/home/000000/users/.home/domains/wordmove.com/html" # use an absolute path here

  database:
    name: "db000000_1clk_wordpress_00000000000000000"
    user: "wordpress_000000"
    password: "000000"
    host: "internal-db.s000000.gridserver.com"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
     host: "s000000.gridserver.com"
     user: "wordmove.com"
  #   password: "xxxxxx" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]

```
