### ISSUE TITLE
Database string replacement

### ISSUE THREAD

**Issue by generousdesignr** [welaika/wordmove#340]
I ran into a string replace problem within my environment. My FTP user connects to mydomain.com where I have my "public" folder with Wordpress named as "web". So I created this config:

```
local:
  vhost: "http://mydomain.local"
  wordpress_path: "/var/www/mydomain/public"
  database: ...

prod:
  vhost: "http://mydomain.com"
  wordpress_path: "web"
  database: ...
```

With this config when I pull the database I end up with all string containing "web" replaced with "/var/www/mydomain/public/" in the SQL dump. For example a simple mention of "webshop" will be "/var/www/mydomain/public/shop" or an attachment containing the like "terms_and_conditions_web.pdf" will be "terms_and_conditions_/var/www/mydomain/public/.pdf". 

Any idea how could I avoid this? Isn't this a more generic problem when the wordpress path is a single directory and without slashes? (I tried to use `web/` as `wordpress_path` which narrowed down the replacements.)

**Comment by kLOsk** [comment]
You should use an absolute path ie:

<code>wordpress_path: "/web" # use an absolute path here</code>

**Comment by pioneerskies** [comment]
@generousdesignr if what @kLOsk suggested isn't enough to make it works, please try what is suggested in our README here https://github.com/welaika/wordmove#ftp

**Comment by agd-uc** [comment]
Using absolute path in `wordpress_path` as @kLOsk suggested I get `553 Can't open that file: No such file or directory`. Which I think makes sense as my user connects and has access only to the parent directory of aforementioned `web` (absolute path is  `/var/www/sites/mydomain/web`). Using absolute path alone or with combination with path I get another error:
`wordmove/wordpress_directory.rb:26:in 'join': no implicit conversion of nil into String (TypeError)`

**Comment by generousdesignr** [comment]
Using absolute path in wordpress_path as @kLOsk suggested I get `553 Can't open that file: No such file or directory`. Which I think makes sense as my user connects and has access only to the parent directory of aforementioned `web` (absolute path is `/var/www/sites/mydomain/web`). Using absolute path alone or with combination with path I get another error:
`wordmove/wordpress_directory.rb:26:in 'join': no implicit conversion of nil into String (TypeError)`

**Comment by pioneerskies** [comment]
Just to be sure: now your `prod` section looks like this?

```
prod:
  vhost: "http://mydomain.com"
  wordpress_path: "/web"
  wordpress_absolute_path: "/var/www/sites/mydomain/web"
```
