### ISSUE TITLE
still having "No valid adapter found"

### ISSUE THREAD

**Issue by faddah** [welaika/wordmove#343]
Hello,

I am also still having the problem with your wordmove Ruby Gem tool for WordPress deployment where you get "No valid adapter found" — same as what was reported in #96.

Here is what I get whenever I try and run with either just `$ wordmove push --all` or even `$  wordmove push -d -t --all` —

```Bash

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:24:in `deployer_for': No valid adapter found. (Wordmove::NoAdapterFound)
	from /usr/local/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:80:in `push'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:22:in `load'
	from /usr/local/bin/wordmove:22:in `<main>'

```

I read all of the back-and-forth instruction given to various people about the `Movefile` and indenting properly with YAML. And yes, I ran my `Movefile` through the on-line [YAML linter](http://www.yamllint.com/) and it passed just fine —

    IMG removed due to sensitive data reported in it

Here is my Movefile (private info replaced in brackets, but in the Movefile i do have the actual correct values) —

```YAML

local:
  vhost: "http://127.0.0.1:8080/wp_martian/"
  wordpress_path: "/Users/yuetsu/Documents/code/web\ site\ projects/martian\ arts/martian_vm/wp_martian" # use an absolute path here

  database:
    name: "wp_martian"
    user: "martian"
    password: "[LOCAL-DB-PASSWORD]"
    host: "localhost"

production:
  vhost: "http://140moviereview.com/wp_transfer_test"
  wordpress_path: "/home1/faddah/public_html/wp_transfer_test" # use an absolute path here

  database:
    name: "faddah_wp_martian"
    user: "[USER-NAME]"
    password: "[PASSWORD]"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
    host: "198.57.246.22:2222"
    user: "faddah"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]


```

Could you please take a look at this and see what I am missing here and why I am getting this `No valid adapter found` error message when trying to do a push with wordmove? Any help here would be greatly appreciated.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by pioneerskies** [comment]
Ouch...well...there seems to be all good...

    wordmove push -d -t --all

is not a good combination. I'd try - for the sake of troubleshooting -

    wordmove push -t -e production

and report here the error. If it will be the same I'll try to setup a fresh WP and use your Movefile.

**Comment by pioneerskies** [comment]
Sorry @faddah for the edit to your post, but in the screenshot there were sensitive auth data.

**Comment by faddah** [comment]
hi @pioneerskies ,

you can go ahead and close this one. i found something in the Movefile that was incorrect or it was a permissions thing on the server, one or both of those. i don't remember now, but i fixed it and tried the move with both wordmove and the WP Plugin Duplicator and both worked fine. thank you for the help.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
hi @pioneerskies ,

thank you for responding. and i understand about removing the image and thank you for that. silly me for forgetting to blur that out. i went ahead and deleted it from my imgur.com account also.

this is with your wordmove v2.0.0, by the way.

ok, so i figured out what i was doing wrong previously, or at least i'm a bit further along. I had for my server and port in the `ssh` section of the `Movefile` as this —

```Bash

  ssh:
    host: "198.57.246.22:2222"
    user: "faddah"

```

... because the port on my shared web host for ssh is 2222 instead of the standard 22. but i read further down in the comments in the `Movefile` and saw i needed to put the port on a separate line. so i did —

```Bash

  ssh:
    host: "198.57.246.22:2222"
    user: "faddah"
    port: "2222"

```

... and suddenly... it all worked! with `wordmove --all`... mostly. anyway, you can close this out.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by pioneerskies** [comment]
Oh really cool to hear that. The rightest syntax would be

```yml
ssh:
    host: "198.57.246.22"
    user: "faddah"
    port: "2222"
```

You can also have an in depth explanation on the `ssh` section in [this](https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained) wiki page :)

Enjoy and see you.
