### ISSUE TITLE
ssh identities

### ISSUE THREAD

**Issue by espretto** [welaika/wordmove#346]
Hello,
I'd like to make a feature request for ssh identities. I use wordmove inside a VVV machine with ssh. Works great, but both the push and pull commands ask me several times for the remote user's password. Now I do have an authorized public key, but I do so for every project and usually manage them via `~/.ssh/config`. It would be great if the ssh section of the `Movefile` had an entry to specifiy the ssh identity to be used or rather a commandline option for `wordmove` since identities may vary among the developers. I imagine sth like this:
```yaml
local:
  [...]
live:
  [...]
  ssh:
    host: ...
    user: ...
    identityFile: <path/to/private/key>
    # or
    identity: <name-of-identity>
```
Swapping out a symbolic link at `~/.ssh` to point to the right key-pair isn't an option either since vagrant depends on it.
