### ISSUE TITLE
vvv movefile database example

### ISSUE THREAD

**Issue by joefraley** [welaika/wordmove#347]
Something that would be really helpful is a working example of a Movefile for a VVV environment. I think it has a place here: https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant)

I would happily add it myself, but I have not gotten this to work yet. I'm confused by the distinction between the database username/password from the perspective of an individual wordpress install vs the mysql username/password from the perspective of the VVV instance.

Compare this wiki: https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained
with the VVV docs: https://github.com/Varying-Vagrant-Vagrants/VVV#credentials

```
local:
  database:
    name: "mydatabase"
    user: "root" # is this mysql or wordpress database?
    password: "toor" # is this mysql or wordpress database?
    host: "localhost" # does this work on VVV, or should it read 127.0.0.1? see below     
    port: "3306"
    charset: "utf8"
    mysqldump_options: "--max_allowed_packet=50MB" # Only available if using SSH
```

Note about host: as suggested in their official docs: https://github.com/varying-vagrant-vagrants/vvv/wiki/Connecting-to-MySQL

> For MySQL Host, enter 127.0.0.1 (note - localhost will not work as that specifies a socket connection).

**Comment by pioneerskies** [comment]
Hi @joefraley :)

> is this mysql or wordpress database?

What does it mean? On the VVV docs you have 3 things- in order:

* Mysql ad-hoc user with permissions granted on WP DB: `wp`
* Wordpress backend user: `admin`
* Mysql root user: root

In `Movefile`:

* we talk about MySQL database in the database section. There is no semantic difference between speaking about "wordpress database" and "mysql database": you are referencing the same object.
* ad `host` entry you should know your environment configuration. I use localhost. 127.0.0.1 should work all the way long, but in the VVV case I strongly suggest to follow the VVV's instruction because you are inside its virtual machine.

That said I'm thinking about

```yml
local:
  database:
    name: "wordpress_default"
    user: "wp"
    password: "wp"
    host: "127.0.0.1"
    port: "3306"
    charset: "utf8"
    mysqldump_options: "--max_allowed_packet=50MB" # Only available if using SSH
```

Please keep in mind that as far as weLaika warmly appreciate the VVV team work, we don't use that dev stack internally, so you should involve someone from the VVV team to have more in depth help about it.

Cheers
