### ISSUE TITLE
Support Ruby script to configure wordmove instead of YAML

### ISSUE THREAD

**Issue by morrislaptop** [welaika/wordmove#362]
Hi, 

I like in Capistrano there is deploy.rb, which is a Ruby script so I can set things dynamically. For example I can load my .env file to read the local domain name. 

Since the Movefile is a static YAML file, I can't set things dynamically. Is there a possibility for this?

Thanks,
Craig

**Comment by pioneerskies** [comment]
This is an example of what we do in our dev team:

```
⟩ cat Movefile
local:
  vhost: "http://localhost:8080"
  wordpress_path: "<%= ENV['WORDPRESS_WORKS_PATH'] %>/tessile"
```

Obsiously the global $WORDPRESS_WORKS_PATH is exported by our dotfiles as per shared practice; but the spot is on: `Movefile` is not static since you can evaluate ruby code inside it starting from #145 

Consider to close the issue if this is what you need :)

Cheers
