### ISSUE TITLE
MySQL Server Has Gone Away

### ISSUE THREAD

**Issue by maiorano84** [welaika/wordmove#372]
This had been touched on in issue #236 but I wanted to double-check here in case I could be missing something.

I have 3 remote environments - each one exists as a separate directory on the same remote server - and 1 local environment. Interestingly, a database push from local to either my Dev or Staging environments will complete without issue. However, a push from local to Production will fail with a MySQL Server has gone away error.

`wordmove push -e dev -d` - Works
`wordmove push -e staging -d` - Works
`wordmove push -e production -d` - Fails

- The same version of MySQL is used across all three databases
- The same settings are used across all three databases (including wait_timeout and max_allowed_packet)

**This does not appear to be the fault of Wordmove itself**, but rather an issue somewhere either in my Wordmove file settings, or something on the server itself that could be rejecting the packet. The purpose of this issue is primarily to get another set of eyes on this for any other ideas that I might not be seeing.

Below are the contents of my Movefile (sans identifying information):

```
local:
  vhost: "http://wordpress.valet"
  wordpress_path: "/path/to/local/bedrock/base/web"

  database:
    name: "local_db"
    user: "root"
    password: "secret"
    host: "127.0.0.1"

  paths: 
    wp_content: "wp/wp-content"
    uploads: "app/uploads"
    plugins: "app/plugins"
    mu_plugins: "app/mu-plugins"
    themes: "app/themes"
    languages: "app/languages"

dev:
  vhost: "https://dev.wp-project.com"
  wordpress_path: "/path/to/remote/dev/web"

  database:
    name: "wp_dev"
    user: "wp_user"
    password: "secret"
    host: "localhost"

  paths:
    wp_content: "wp/wp-content"
    uploads: "app/uploads"
    plugins: "app/plugins"
    mu_plugins: "app/mu-plugins"
    themes: "app/themes"
    languages: "app/languages"

  ssh:
    host: "wp-project.com"
    user: "system_user"

staging:
  vhost: "https://qa.wp-project.com"
  wordpress_path: "/path/to/remote/qa/web"

  database:
    name: "wp_qa"
    user: "wp_user"
    password: "secret"
    host: "localhost"

  paths:
    wp_content: "wp/wp-content"
    uploads: "app/uploads"
    plugins: "app/plugins"
    mu_plugins: "app/mu-plugins"
    themes: "app/themes"
    languages: "app/languages"

  ssh:
    host: "wp-project.com"
    user: "system_user"

production:
  vhost: "https://wp-project.com"
  wordpress_path: "/path/to/remote/prod/web"

  database:
    name: "wp"
    user: "wp_user"
    password: "secret"
    host: "localhost"

  paths:
    wp_content: "wp/wp-content"
    uploads: "app/uploads"
    plugins: "app/plugins"
    mu_plugins: "app/mu-plugins"
    themes: "app/themes"
    languages: "app/languages"

  ssh:
    host: "wp-project.com"
    user: "system_user"
```
Any ideas?
