### ISSUE TITLE
Error: `clone': can't clone NilClass (TypeError)

### ISSUE THREAD

**Issue by brightpixels** [welaika/wordmove#389]
I am getting an obscure error. Please see screenshot. This happens when I try to pull anything like database, them, uploads, etc

![screen shot 2017-04-24 at 16 31 29](https://cloud.githubusercontent.com/assets/5403134/25345100/00b03f4c-290c-11e7-8219-045b5d5fa09f.png)

**Comment by pioneerskies** [comment]
Hi @brightpixels ,

seems clear to me you have a malformed Movefile; would you like to post it here (formatted)?

**Comment by brightpixels** [comment]
```yaml
devcontainer:
  vhost: "*********"
  wordpress_path: "***********" # use an absolute path here

  database:
    name: "*********"
    user: "*********"
    password: "*********"
    host: "*********"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

build02:
  vhost: "*********"
  wordpress_path: "*********" # use an absolute path here

  database:
    name: "*********"
    user: "*********"
    password: "*********"
    host: "*********"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=50MB" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  ssh:
    host: "*********"
    user: "*********"
```
