### ISSUE TITLE
Error: "No such file or directory" and "(Errno::ENOENT)"

### ISSUE THREAD

**Issue by th3car3tak3r** [welaika/wordmove#390]
I'm a new Wordmove user, but I've poked around for hours and can't find a solution to below error message I get when trying to push my local database to remote. Does anyone know the solution to this, or what I'm doing wrong?

```
▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=localhost --user=root --password=password --result-file="/var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql" wordpress_alpha
gzip --best --force "/var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql"
   remote | gzip --best --force "/var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql"
   remote | get: /var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql.gz /Users/primary/Sites/alpha/alpha.dev/wp-content/production-backup-1494462383.sql.gz
   remote | delete: /var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql.gz
    local | mysqldump --host=XXX.X.X.X --user=alpha --password=password --result-file="/Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql" alpha_db
    local | adapt dump
gzip --best --force "/Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql"
    local | gzip --best --force "/Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql"
   remote | put: /Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql.gz /var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql.gz
gzip -d --force "/var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql.gz"
   remote | gzip -d --force "/var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql.gz"
   remote | mysql --host=localhost --user=root --password=password --database=wordpress_alpha --execute="SET autocommit=0;SOURCE /var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql;COMMIT"
   remote | delete: /var/www/vhosts/mysite.com/httpdocs/wp-content/dump.sql
    local | delete: '/Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql.gz'
/Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:227:in `delete': No such file or directory - /Users/primary/Sites/alpha/alpha.dev/wp-content/dump.sql.gz (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:227:in `local_delete'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:24:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:86:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:85:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```

Here is my movefile: 
```

local:
  vhost: "http://alpha.dev"
  wordpress_path: "/Users/primary/Sites/alpha/alpha.dev" # use an absolute path here

  database:
    name: "alpha_db"
    user: "alpha"
    password: "xxxxxxxxxx"
    host: "xxx.x.x.x"

production:
  vhost: "http://mysite.com"
  wordpress_path: "/var/www/vhosts/mysite.com/httpdocs" # use an absolute path here

  database:
    name: "wordpress_alpha"
    user: "root"
    password: "xxxxxxxxxx"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
    host: "xxx.xx.xxx.xx"
    user: "root"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]
```
