### ISSUE TITLE
rsync_options does not keep necessary quotes for needed option

### ISSUE THREAD

**Issue by freedog96150** [welaika/wordmove#392]
Been trying to figure out how to get the rsync_options section of the Movefile to respect the necessary quotes for an rsync option.  What I need is as below:

`--rsync-path="sudo rsync" or alternately --rsync-path='sudo rsync'`

I have tried single quotes, double quotes and escaping with backslashes.  In all configurations attempted, the final output reverts to --rsync-path=sudo rsync which causes an error when run.  If I copy/paste the command, add the needed quotes, the command runs as expected.  I am sure that I am missing something easy that will allow me to set this parameter in the Movefile and have it properly inserted.  Any suggestions?

**Comment by freedog96150** [comment]
Should have included the relevant portion of my Movefile.
```
ssh:
  host: "1.2.3.4"
  user: "someuser"
  rsync_options: "--protect-args --verbose --rsync-path='sudo rsync'" 
```
