### ISSUE TITLE
failed to allocate memory (NoMemoryError)

### ISSUE THREAD

**Issue by elebumm** [welaika/wordmove#397]
I am trying to push a large database on to the server but I get this error `/usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.2/lib/wordmove/sql_adapter.rb:44:in `gsub!': failed to allocate memory (NoMemoryError)`

I am unsure how to fix this. Is this something wrong with Wordmove or is it something on my part?

Here is the Movefile:

```
local:
  vhost: "http://mysite.dev"
  wordpress_path: "/srv/www/mysite/htdocs" # use an absolute path here

  database:
    name: "mysite"
    user: "root"
    password: "root"
    host: "localhost"

production:
  vhost: "http://mysite.com"
  wordpress_path: "/var/www/mysite.com/htdocs" # use an absolute path here

  database:
    name: "mydatabase"
    user: "root"
    password: "passwordhere"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
    host: "ssh"
    user: "root"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
    rsync_options: "-og --chown=www-data:www-data --no-perms --chmod=ugo=rwX" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]

```
