### ISSUE TITLE
`parse': (<unknown>): did not find expected '-' indicator while parsing a block collection

### ISSUE THREAD

**Issue by andersedvardsen** [welaika/wordmove#399]
```
/Users/myusersfolder/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych.rb:377:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 27 column 5 (Psych::SyntaxError)
	from /Users/myusersfolder/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /Users/myusersfolder/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /Users/myusersfolder/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych.rb:291:in `safe_load'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.2/lib/wordmove/deployer/base.rb:50:in `fetch_movefile'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.2/lib/wordmove/deployer/base.rb:10:in `deployer_for'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.2/lib/wordmove/cli.rb:80:in `push'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.2/exe/wordmove:6:in `<top (required)>'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `load'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `<main>'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/myusersfolder/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pioneerskies** [comment]
https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting

**Comment by andrewvink** [comment]
Hey Guys, 

I've come across the same error.

**Using:**
Windows x64
Laravel Homestead + Virtual Box

Installed Ruby and have WordMove successfully working with another site. Both Pull & Push are working perfectly.

The error occurs on a new website - I'm assuming this error is happening due to the remote server config.


```
vagrant@homestead:~/mysite$ wordmove pull --all

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:377:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 27 column 5 (Psych::SyntaxError)
        from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
        from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:325:in `parse'
        from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:291:in `safe_load'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:50:in `fetch_movefile'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:10:in `deployer_for'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/lib/wordmove/cli.rb:63:in `pull'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/bin/wordmove:22:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/bin/wordmove:22:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

My WordMove File

```
global:
  sql_adapter: "default"

local:
  vhost: "http://mysite.dev"
  wordpress_path: "/home/vagrant/mysite" # use an absolute path here

  database:
    name: "mysite"
    user: "homestead"
    password: "secret"
    host: "localhost"

production:
  vhost: "http://mysite.co.za"
  wordpress_path: "/usr/home/mysite_usr/public_html" # use an absolute path here

  database:
    name: "mysite"
    user: "mysite_live"
    password: "mysite_password"
    host: "mysite_host"
    port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  # ssh:
      host: "mysite_host"
      user: "mysite_user"
      password: "mysite_password" # password is optional, will use public keys if available.
      port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #   user: "user"
  #   password: "password"
  #   host: "host"
  #   passive: true
  #   scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]

```
