### ISSUE TITLE
Wordmove doesn't upload files, only database

### ISSUE THREAD

**Issue by marko-stimac** [welaika/wordmove#404]
I have trouble uploading files using "Wordmove push --all". None of the files are uploaded but database upload works great. I don't get any error message, what could be wrong?
I am on Windows 7

![_uftmcn0qkah2wdpvr9nrq](https://user-images.githubusercontent.com/6604806/27130165-73ca4a2e-5105-11e7-8894-4f7a92e0e590.jpeg)

```
global:
  sql_adapter: "default"

local:
  vhost: "http://localhost/_posao/tema_1"
  wordpress_path: "C:/wamp64/www/_posao/tema_1" # use an absolute path here

  database:
    name: "tema_1"
    user: "root"
    password: ""
    host: "localhost"

production:
  vhost: "https://test.mysite.com/tema_1"
  wordpress_path: "/var/www/html/tema_1" # use an absolute path here

  database:
    name: "tema_1"
    user: "root"
    password: "password"
    host: "localhost"

  ssh:
    host: "5.113.122.17"
    user: "root"
    password: "mypassword!" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
    rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.


```
