### ISSUE TITLE
`parse': (<unknown>): did not find expected '-'

### ISSUE THREAD

**Issue by dannygsmith** [welaika/wordmove#409]
I am running macOS Sierra version 10.12.6
Wordmove is version 2.1.3
Ruby is the latest version 2.4.1_1 install via homebrew
I have my public and private keys setup so I don't need a password
When I run `wordmove push --all` I get the following error:

$ wordmove push --all

```▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/psych.rb:377:in 'parse': (<unknown>):
   did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
   from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/psych.rb:377:in 'parse_stream'
   from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/psych.rb:325:in 'parse'
   from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/psych.rb:291:in 'safe_load'
   from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:50:in 'fetch_movefile'
   from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:10:in 'deployer_for'
   from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:80:in 'push'
   from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in 'run'
   from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in 'invoke_command'
   from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in 'dispatch'
   from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in 'start'
   from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/exe/wordmove:6:in '<top (required)>'
   from /usr/local/bin/wordmove:22:in 'load'
   from /usr/local/bin/wordmove:22:in '<main>'
```

```
global:
  sql_adapter: "default"

local:
  vhost: "http://tabber.dev"
  wordpress_path: "/Users/someuser/Sites/tabber/app/public" # use an absolute path here

  database:
    name: "local"
    user: "root"
    password: "********"
    host: "localhost"

production:
  vhost: "http://tabber.somedomain.me"
  wordpress_path: "/home/someuser/public_html/tabber" # use an absolute path here

  database:
    name: "someuser"
    user: "someuser"
    password: "somepassword"
    host: "somehost"

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

 ssh:
      host: "somehost"
      user: "someuser"
      port: 18765 # Port is optional
```
