### ISSUE TITLE
Can't pull any data from the server, create only directories and return error.

### ISSUE THREAD

**Issue by akwa770** [welaika/wordmove#410]
this is the error i got:
![image](https://user-images.githubusercontent.com/16808071/29405697-51d491e4-8347-11e7-8cea-8aa53fd2cc7c.png)

this is my file:

```yaml
global:
  sql_adapter: "default"

local:
  vhost: "http://localhost:80"
  wordpress_path: "C:/xampp/htdocs/webnow-clone2" # use an absolute path here

  database:
    name: "webnow-clone"
    user: "root"
    password: ""
    host: "localhost"

production:
  vhost: "http://mysite.com"
  wordpress_path: "/home6/webnowco/" # use an absolute path here

  database:
    name: "webnowco_webnow"
    user: "user_mame"
    password: "pass"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  # ssh:
  #   host: "host"
  #   user: "user"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  ftp:
   user: "user_name"
   password: "pass"
   host: "host"
   passive: true
   # scheme: "ftps" # default "ftp"

# staging: # multiple environments can be specified
#   [...]
```

Thanks for your help.
