### ISSUE TITLE
Error when trying to pull 

### ISSUE THREAD

**Issue by q-admin** [welaika/wordmove#417]
When I try to do a pull of the database I get this error: 
![screen shot 2017-10-24 at 11 16 15 am](https://user-images.githubusercontent.com/4582767/31951694-d37a2b42-b8ac-11e7-94bd-8325ae7de95a.png)

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/matt/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:24:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/lib/wordmove/cli.rb:63:in `pull'
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/matt/.rvm/gems/ruby-2.4.1/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
	from /Users/matt/.rvm/gems/ruby-2.4.1/bin/wordmove:23:in `load'
	from /Users/matt/.rvm/gems/ruby-2.4.1/bin/wordmove:23:in `<main>'
	from /Users/matt/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matt/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'`
```

I've ran my Movefile a yaml linter and it comes back ok. Any ideas? 

```yaml
local:
  database:
    host: localhost
    name: site_wp
    password: root
    user: root
  paths:
    languages: app/languages
    mu_plugins: app/mu-plugins
    plugins: app/plugins
    themes: app/themes
    uploads: app/uploads
    wp_content: wp/wp-content
  vhost: "http://mysite.dev"
  wordpress_path: /Users/matt/Projects/mysite
staging:
  database:
    host: localhost
    name: site_wp
    password: "__password__"
    user: site_wp
  exclude:
    - .git/
    - .gitignore
    - .sass-cache/
    - bin/
    - tmp/*
    - Gemfile*
    - Movefile
    - wp-config.php
    - wp-content/*.sql
  paths:
    languages: app/languages
    mu_plugins: app/mu-plugins
    plugins: app/plugins
    themes: app/themes
    uploads: app/uploads
    wp_content: wp/wp-content
  ssh:
    host: "__serverIPaddress__"
    port: 22
    rsync_options: "--verbose"
    user: serveruser
  vhost: "http://mytestserver.com"
  wordpress_path: /var/www/vhosts/mytestserver.com/mysite
```
