### ISSUE TITLE
Error on push - fresh scotchbox install - rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]

### ISSUE THREAD

**Issue by ryanfurtner** [welaika/wordmove#418]
I am getting this error if I try to push my files on a new scotchbox setup. I was getting a different error before. Installing sshpass fixed that. I cannot for the life of me figure this one out:

```
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```
here is my movefile (with domains and passwords changed)

```
global:
  sql_adapter: "default"

local:
  vhost: "http://domain.local"
  wordpress_path: "/var/www/public" # use an absolute path here

  database:
    name: "domain"
    user: "root"
    password: "root"
    host: "localhost"

production:
  vhost: "https://domain.domain.com"
  wordpress_path: "/public_html" # use an absolute path here

  database:
    name: "dbname"
    user: "dbuser"
    password: "password"
    host: "host"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

  ssh:
     host: "13.111.111.11"
     user: "sitedomain"
     password: "password" # password is optional, will use public keys if available.
     rsync_options: "--verbose" # Additional rsync options, optional
```
