### ISSUE TITLE
Error on pull - No nodename nor servername

### ISSUE THREAD

**Issue by Glimbrant** [welaika/wordmove#419]
When i do push/pull db, just files or all i get no nodename nor servername.

What could be the problem?

**Ruby**
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**WordMove**
2.1.32.1.3

```
Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=root --result-file="/Users/andreasglimbrant/Sites/wasabiweb/test/wp-content/local-backup-1509008821.sql" test
gzip --best --force "/Users/andreasglimbrant/Sites/wasabiweb/test/wp-content/local-backup-1509008821.sql"
    local | gzip --best --force "/Users/andreasglimbrant/Sites/wasabiweb/test/wp-content/local-backup-1509008821.sql"
   remote | mysqldump --host=localhost --user=root --password=XXX --result-file="/var/www/test/wp-content/dump.sql" test
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/socket.rb:227:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/socket.rb:227:in `foreach'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/socket.rb:617:in `tcp'
	from /usr/local/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/photocopier-1.1.3/lib/photocopier/ssh.rb:70:in `session'
	from /usr/local/lib/ruby/gems/2.4.0/gems/photocopier-1.1.3/lib/photocopier/ssh.rb:43:in `exec!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:50:in `remote_run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:63:in `download_remote_db'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh/default_sql_adapter.rb:28:in `adapt_remote_db!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:35:in `pull_db'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:69:in `block in pull'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `handle_options'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:68:in `pull'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```

**Movefile**
```
global:
  sql_adapter: default
local:
  database:
    host: localhost
    name: test
    password:
    user: root
  vhost: "http://localhost/wasabiweb/test"
  wordpress_path: /Users/andreasglimbrant/Sites/wasabiweb/test
production:
  database:
    host: localhost
    name: test
    password: xxx
    user: root
  exclude:
    - .git/
    - .gitignore
    - .sass-cache/
    - node_modules/
    - bin/
    - tmp/*
    - Gemfile*
    - Movefile
    - wp-config.php
    - wp-content/*.sql.gz
  ssh:
    host: example.com
    port: 220000
    user: xxx
  vhost: "http://example.com/test"
  wordpress_path: /var/www/test
```
