### ISSUE TITLE
No valid adapter found. (Wordmove::NoAdapterFound)

### ISSUE THREAD

**Issue by ryscript** [welaika/wordmove#420]
Hello,
Thanks for the great tools.

So I manage to create a Movefile and validated in http://www.yamllint.com/, however, I'm having an issue pulling remote host.

Command
`wordmove pull  --all`

I only have a single remote host so `-e` is not necessary but I do try it too but unfortunately with the same result.

Movefile
```
global:
  sql_adapter: "default"
 
local:
  vhost: "http://devserver.local/"
  wordpress_path: "/PHP Project/wordpress" # use an absolute path here
  
  database:
    name: "ryscript"
    user: "root"
    password: "root"
    host: "localhost"
    
production:
  vhost: "http://www.domain.com/"
  wordpress_path: "/home/USER/public_html/" # use an absolute path here
  
  database:
    name: "DB_NAME"
    user: "USER"
    password: "PASSWORD"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH
    
  exclude:
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"
```

Things to consider (though with the same result)
1. I run the command in a directory with just `Movefile` in it.
2. Run the command in local WP directory
3. Adding different command option e.g. `-t` or `-p`

Thanks
