### ISSUE TITLE
Ongoing issues with error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock'

### ISSUE THREAD

**Issue by nailbrain** [welaika/wordmove#426]
Hi,

I've had ongoing issues with the 2002 error.

I've gone through two threads that look like they we resolved but still can't fix the problem.

I hope you can help me.

After hunting around for my my.cnf file I found it in '/usr/local/opt/mysql/my.cnf'

Looks like I installed mySQL via home brew.

I changed the file to the following: 

```
# These are commonly set, remove the # and set as required.
# basedir = .....
# datadir = .....
# port = .....
# server_id = .....
# socket = /Applications/MAMP/tmp/mysql/mysql.sock
```

I also tried changing it to:

```
# These are commonly set, remove the # and set as required.
# basedir = .....
# datadir = .....
# port = .....
# server_id = .....
# socket = /tmp/mysql.sock
```

When I ran 'sudo lsof | grep mysql.sock' it listed both '/Applications/MAMP/tmp/mysql/mysql.sock' and '/tmp/mysql.sock'.

I closed each one down independantly so only one was running and tested the above changes in my my.cnf file. 

I then copied the my.cnf file to /etc/my.cnf and the the same as the above but with no luck.

Here is a copy of my wordmove file:

```
local:
  vhost: "http://localhost:8888/brett-dev-rebuild/"
  wordpress_path: "/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild" # use an absolute path here

  database:
    name: "brettdevrebuild"
    user: "root"
    password: "root"
    host: "localhost"
```

And here is a copy of the terminal error:

```
local | mysqldump --host=localhost --user=root --password=root --result-file="/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild/wp-content/dump.sql" brettdevrebuild
Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
/Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:141:in `run': Return code reports an error (Wordmove::ShellCommandError)
```

I'm not quite sure if these settings are correct or what I am doing wrong.

**Comment by pioneerskies** [comment]
Hello there!

First try: change `localhost` to `127.0.0.1` if you are on a Mac
Second try: use `mysql_adapter: 'wplci'` as per new documentation. If your own wordpress can connect to the database, that adapter will success too! Keep in minf `wp-cli` is a required peer dependancy for this adapter ;)

Hope you'll succeed.

Let me know

**Comment by nailbrain** [comment]
Thanks @pioneerskies for the quick reply.

I'm still getting the exact same error. I changed local host to 127.0.0.1.

I installed WPCLI using the following [guide](https://make.wordpress.org/cli/handbook/installing/).

And changed the mysql_adapter.

```
global:
  sql_adapter: "wpcli"

local:
  vhost: "127.0.0.1"
  wordpress_path: "/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild" # use an absolute path here

  database:
    name: "brettdevrebuild"
    user: "root"
    password: "root"
    host: "localhost"
```

**Comment by pioneerskies** [comment]
@nailbrain I remembered this old ticket while replying to you on a newer one.

`wordmove doctor` will also check if wordmove will be able to connect to the local database. If it won't be able, it means that `mysqldump` command can't access to the database. But this problem should be solved probably outside of the wordmove scope:

    mysqldump --host=127.0.0.1 --user=root --password=root --result-file="/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild/wp-content/dump.sql" brettdevrebuild

should have to work on its own behalf.

**Comment by pioneerskies** [comment]
Holy cow! @nailbrain I've re-read your issue and spotted out a thing: you have MAMP and you have also installed mysql via brew? This can cause problem with commands in $PATH. Let me know if you mind.

**Comment by nailbrain** [comment]
Hi @pioneerskies I've tried running `wordmove doctor` but got the error `Could not find command "doctor".`

Do you think it could be related to having multiple instances of mySQL installed?

I'm assuming I should uninstall mySQL using brew? Does Wordmove work well with MAMP?

**Comment by pioneerskies** [comment]
@nailbrain I think it's only related to an outdated version of the gem 😂 🙈

**Comment by pioneerskies** [comment]
Just saying: Wordmove merely ignore how you have installed MySQL. It just want to know how to connect to a server instance just like any other client, so don't worry ;)

**Comment by pioneerskies** [comment]
Let's resume; I got a bit confused in some previous posts...my bad.

when I asked you

> First try: change localhost to 127.0.0.1 if you are on a Mac

you actually changed the `local.vhost`, not `local.database.host`

```yaml
global:
  sql_adapter: "wpcli"

local:
  vhost: "127.0.0.1"
  wordpress_path: "/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild" # use an absolute path here

  database:
    name: "brettdevrebuild"
    user: "root"
    password: "root"
    host: "localhost"
```

I meant

```yml
database:
    name: "brettdevrebuild"
    user: "root"
    password: "root"
    host: "127.0.0.1"
```

This can't return the same error, because you force `mysqldump` to connect via TCP leaving the `socket` connection away. This is not how Wordmove works, but just how `mysql` and `mysqldump` work.

___

> Do you think it could be related to having multiple instances of mySQL installed?

So: `wordmove doctor` is not related: you just have an old `wordmove` version. I hope you upgraded to the latest since I can help supporting only on the latest (non beta) version.

Your problem with MySQL could be related to having multimple MySQL instances installed. But it is not a problem brought by Wordmove it's just a little mess on the development system ;) Requesting a TCP connection to 127.0.0.1 could bypass some of this confusion.

Where the confusion could be? When using `localhost` as DB host, `mysqldump` will search for a socket. Where the socket is is configured by default to `/i/dont/know/where`. Having multiple MySQL installed?
Ok: both will have their command line tool. Using brew's `mysqldump` will use its own defaults, using MAMP's `mysqldump` will use its own defaults.

So: which `mysqldump` is wordmove calling? You should know that with

    which mysqldump
    which mysql

and you have to consider that the precedence between brew's commands and MAMP's commands is controlled by you shell's $PATH. If you start MAMP's MySQL server and then use brew's `mysqldump` it *could* work even if they are from different versions, **but** not if they are searching for different `socket`s

___

I hope to have re-ordered ideas a bit and I hope you'll have the time and the scenario to test these assumptions. If it is no more the case, I'd be glad if you'll close the issue just to keep things clean ;)

Cheers
