### ISSUE TITLE
no implicit conversion of Symbol into Integer (TypeError)

### ISSUE THREAD

**Issue by nailbrain** [welaika/wordmove#449]
I'm getting the following error when using the command: wordmove pull -all

Any idea what the problem might be?

Many thanks!

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:22:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:22:in `deployer_for'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-2.1.3/lib/wordmove/cli.rb:63:in `pull'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/wordmove:23:in `load'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/wordmove:23:in `<main>'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nailbrain** [comment]
My config file:

```
  global:
  sql_adapter: "wpcli"

local:
  vhost: "localhost:8888"
  wordpress_path: "/Users/brettgolding/Google Drive/htdocs/brett-dev-rebuild" # use an absolute path here

  database:
    name: "brettdevrebuild"
    user: "root"
    password: "root"
    host: "localhost"

production:
  vhost: "http://box5159.temp.domains/~brettdev/"
  wordpress_path: "/home1/brettdev/public_html/" # use an absolute path here

  database:
    name: "brettdev_brettdev"
    user: "brettdev_brett"
    password: "password"
    host: "localhost"
    # port: "3308" # Use just in case you have exotic server config
    # mysqldump_options: "--max_allowed_packet=1G" # Only available if using SSH

  exclude:
    - "askchiangmai"
    - "output"
    - "brettdev"
    - ".htaccess"
    - "valueinspiration"
    - "datascience"
    - ".git/"
    - ".gitignore"
    - ".sass-cache/"
    - "node_modules/"
    - "bin/"
    - "tmp/*"
    - "Gemfile*"
    - "Movefile"
    - "wp-config.php"
    - "wp-content/*.sql.gz"

  # paths: # you can customize wordpress internal paths
  #   wp_content: "wp-content"
  #   uploads: "wp-content/uploads"
  #   plugins: "wp-content/plugins"
  #   mu_plugins: "wp-content/mu-plugins"
  #   themes: "wp-content/themes"
  #   languages: "wp-content/languages"

  ssh:
    host: "162.241.224.50"
    user: "brettdev"
  #   password: "password" # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
  #   rsync_options: "--verbose" # Additional rsync options, optional
  #   gateway: # Gateway is optional
  #     host: "host"
  #     user: "user"
  #     password: "password" # password is optional, will use public keys if available.

  # ftp:
  #  user: "brettdevcom"
  #  password: "password"
  #  host: "ftp.ipage.com"
  #  passive: true
  #  scheme: "ftp" # default "ftp"

# staging: # multiple environments can be specified
#   [...]
```
