### ISSUE TITLE
Wordmove commands (inc. wordmove init) throwing errors in Docker Wordpress container

### ISSUE THREAD

**Issue by jamespatrikrichards** [welaika/wordmove#452]
**UPDATE**  realised I was pulling from `production`, rather than `remote` in this comment. However, there is still an issue... see [further down](https://github.com/welaika/wordmove/issues/452#issuecomment-362053083) and the `wordmove init` error in this comment.

Had wordmove working brilliantly on a vagrant box (modified vccw box), but am attempting to move across to Docker to simlify config. I'm attempting to extend the Docker Wordpress image (with up to date Ruby etc.), and hitting an issue that, after much Googling, I'm getting nowhere with. I'm running as root (will this cause issues with wp-cli??), and getting the following issues when I try to run any wordmove command, even `wordmove init`.

Any help would be massively appreciated. It's an awesome tool, and even more awesome when you know how good it is but cant have it!!!

Output of `wordmove pull -d -u -e production`

```
▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/deployer/base.rb:14:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/cli.rb:68:in `pull'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Using movefile.yml:

```
global:
  sql_adapter: default

local:
  vhost: http://local.vhost.co.uk
  wordpress_path: /var/www/html

  database:  # these creds work fine using mysql command to connect to the db
    name: wordpress
    user: root
    password: rootwordpress
    host: db
    port: '3306'
    charset: utf8
    mysqldump_options: --max_allowed_packet=50MB

remote:
  vhost: https://host.co.uk
  wordpress_path: /path/to/wp

  database:
    name: db_name
    user: user
    password: xxxxxxxxxxxx
    host: xxx.xxx.xxx.xxx

  ssh:
    host: host.co.uk
    user: user
    port: 1234
    rsync_options: --verbose
```

Output of `wordmove init`:

```
/usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `initialize': Input/output error @ rb_sysopen - /var/www/html/movefile.yml (Errno::EIO)
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `open'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/create_file.rb:25:in `create_file'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/generators/movefile.rb:12:in `copy_movefile'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/cli.rb:12:in `init'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Output of `wordmove doctor` (the test mysql command looks weird??)

```
▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Validating movefile section: global ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | Formal validation passed

▬▬ Validating movefile section: local ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | Formal validation passed

▬▬ Validating movefile section: remote ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | Formal validation passed

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Checking local database commands and connection ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | `mysql` command is in $PATH
    ✓ success | `mysqldump` command is in $PATH
    ✗ error | We can't connect to the database using credentials
specified in the Movefile. Double check them or try
to debug your system configuration.

The command used to test was:

mysql -u  -h  -e'QUIT'

▬▬ Checking local wp-cli installation ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the respective user:

    sudo -u USER -i -- wp <command>


    ✓ success | wp-cli is correctly installed and up to date

▬▬ Checking rsync ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | rsync is installed at version 3.1.2

▬▬ Checking SSH client ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✓ success | SSH command found
```

**Comment by simonbland** [comment]
Hi @jamespatrikrichards,

I can't tell why you are getting this error when running Wordmove, but I encountered today the same permission problem with wp-cli. It can't be run as root, unless the `--allow-root` flag is given. As Wordmove doesn't call wp-cli with this flag (see [here](https://github.com/welaika/wordmove/blob/v2.4.2/lib/wordmove/sql_adapter/wpcli.rb) and [here](https://github.com/welaika/wordmove/blob/v2.4.2/lib/wordmove/doctor/wpcli.rb) for example), you get the error.

A solution for this is to login as an non-root user inside the container, which means adding something like this in your Dockerfile:

```
RUN useradd wordmove && echo "wordmove:wordmove" | chpasswd && adduser wordmove sudo
RUN mkdir -p /home/wordmove && chown wordmove:wordmove /home/wordmove
USER wordmove
```

However, in your case, you don't seem to be using the `wpcli` adapter, but rather the `default` one:

```
global:
  sql_adapter: default
```

In my experience, with the default adapter, wp-cli is not called when pulling/pushing, only when calling `wordmove doctor`, so this is a false positive, it should not a problem in your case.

I hope at could help at least for this point.

**Comment by simonbland** [comment]
For you information, in my case, I was successful in building an dockerized WordPress environment as described here: [Wordpress development made easy using Docker](https://medium.com/cluetip/wordpress-development-made-easy-440b564185f2).

If you try to go this way, I suggest you to replace the currently outdated [mfuezesi/wordmove](https://hub.docker.com/r/mfuezesi/wordmove/) image with this one: [simonbland/wordmove](https://hub.docker.com/r/simonbland/wordmove/), that I freshly build today.

**Comment by jamespatrikrichards** [comment]
Nice!! Will use your advice for the `wp-cli` issue. Does your image ship with the latest versions of Ruby & Wordmove?

**Comment by simonbland** [comment]
One last thing, I came across the [wocker/wordpress/](https://hub.docker.com/r/wocker/wordpress/) image today, that includes Wordpress as well as Wordmove inside the same image, which seems to be closer to what you are trying to do. Maybe you can use the Dockerfile(s) of this repository as an example, or use/adapt this image directly.

**Comment by simonbland** [comment]
Just in case, I you really want to use Wordmove with WordPress in the same image, you may look at the Dockerfile(s) of [wocker/wordpress](https://hub.docker.com/r/wocker/wordpress/), as an example. This image does exactly this (with other additions however).

**Comment by jamespatrikrichards** [comment]
Hi @simonbland. Thanks for your help and suggestions, but I'm still having the same issue. I'm stumped. I've abandoned adjusting the `wordpress:latest` image to include wordmove, and have instead just included `simonbland/wordmove`. See the `docker-compose.yml` and `movefile.yml` I'm using below - maybe someone can replicate the problem?? I'm assuming it's something stupid like a syntax error in my movefile... but confused as to why `wordmove doctor` reads it ok...

`wordmove doctor` runs fine, except for the error:

```
 ✗ error | We can't connect to the database using credentials
specified in the Movefile. Double check them or try
to debug your system configuration.

The command used to test was:

mysql -u  -h  -e'QUIT'
```
However, if I run `mysql -h db -u root -prootwordpress -D wordpress -P 3306`, from within the wordmove container I can connect fine.

When I try to run , I still get


```
▬▬ Using Movefile: ./Movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/deployer/base.rb:14:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/lib/wordmove/cli.rb:68:in `pull'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/wordmove-2.4.2/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

`docker-compose.yml`:
```
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    restart: on-failure:5
    command: "bash -c apache2-custom.sh"
    volumes:
      - ./certs:/etc/apache2/ssl
      - ./wordpress/wp-content/:/var/www/html/wp-content
      - ./config/wp-init.sh:/usr/local/bin/apache2-custom.sh
      - ./config/apache2-vhosts.conf:/etc/apache2/sites-available/apache2-vhosts.conf

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: on-failure:5
    environment:
      PMA_HOST: db

  wordmove:
    tty: true
    depends_on:
      - wordpress
    image: simonbland/wordmove
    restart: on-failure:5
    container_name: wordmove
    volumes:
      - ./config:/home
      - ./wordpress:/var/www/html
      - ~/.ssh:/root/.ssh

volumes:
  db_data:
```

`movefile.yml`:
```
global:
  sql_adapter: wp-cli

local:
  vhost: http://dev.test.co.uk
  wordpress_path: /var/www/html
  database:
    name: wordpress
    user: root
    password: rootwordpress
    host: db
    port: '3306'
    charset: utf8
    mysqldump_options: --max_allowed_packet=50MB

remote:
  vhost: https://test.co.uk
  wordpress_path: /path/to/wordpress
  database:
    name: wp_db
    user: user
    password: password
    host: '123.456.789.000'

  exclude:
    - .git/
    - .gitignore
    - .sass-cache/
    - node_modules/
    - bin/
    - tmp/*
    - Gemfile*
    - Movefile
    - wp-config.php
    - wp-content/*.sql

  ssh:
    host: test.co.uk
    user: user
    port: 12345
    rsync_options: --verbose
```
