### ISSUE TITLE
I want to deactivate plugin when push -e production

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#455]
I want to deactivate plugin when push -e production.

there's plugin that i only use in staging, but in production i dont need.

so, would be great if there any way to deactivate when i push to my production.

so, when is run
`wordmove push -e production --all
or
wordmove push -e production -p`
i want an option that can set which plugin active and which deactivate.

**Comment by pioneerskies** [comment]
Do you have wp-cli installed in production?

**Comment by byron222** [comment]
yes!

**Comment by pioneerskies** [comment]
Sorry @byron222 for my delay. Busy days.

What I'd do to accomplish your need is to use Wordmove's `hooks`. An example is [here](https://github.com/welaika/wordmove/wiki/YAML-tips#using-local-variables-with-interpolations), but you'll need some differentiations:


```yml
production:
  <% prod_wp_path = "/home/sshwordmove/sshwordmove.welaika.com" %>
  vhost: "http://sshwordmove.welaika.com"
  wordpress_path: <%= prod_wp_path %> # use an absolute path here

  database:
    [...]

  exclude:
    [...]

  ssh:
    [...]

  hooks:
    push:
      after:
        remote:
          - 'cd <%= prod_wp_path %> && wp plugin deactivate debug-bar'
```

Obviously *debug-bar* will be the slug of your very plugin which has to be deactivated :)

Let me know
