### ISSUE TITLE
Move specific DB tables (supporting wildcard names)

### ISSUE THREAD

**Issue by pioneerskies** [welaika/wordmove#468]
Hello,

now that we have slowly moved along the way and we have declared `wp-cli` as a dependency, we have possibility to afford this feature in a secure, standard way.

I'm thinking about solving 2 different problems here:

1. dump only tables with specific prefix
2. dump only certain tables

The config inside `movefile.yml` would look like

```yml
database:
  name: 'mydb'
  password: 'mypwd'
  [...]
  tables:
    - 'wp_posts'
    - 'wp_users'
```

or

```yml
database:
  name: 'mydb'
  password: 'mypwd'
  [...]
  tables:
    - 'wp_*'
```

or a mix

```yml
database:
  name: 'mydb'
  password: 'mypwd'
  [...]
  tables:
    - 'custom_prefix_*'
    - 'wp_posts'
```

The implementation would rely on `wp db tables` command; slow (`wp-cli` is slow to load) but rock solid. I'd cycle over the array of strings `tables` and construct a string from the output of

    wp db tables 'custom_prefix_*' --all-tables

intercepting the use of the wildcard and passing thus to `wp-cli`; or simply appending 'wp_posts' because no wildcard is used.

The resulting `mysqldump` command would be, e.g.:

    mysqldump --host=localhost --user=root --result-file="/Users/fuzzy/dev/sshwordmove/wp-content/dump.sql" --default-character-set=utf8 sshwordmove wp_posts custom_prefix_table1 custom_prefix_table2

___

Tables would be specified for each environment (local and/or remote) based on the desired behaviour. Opening to scenarios where I can pull only `wp_posts` from production, but `wp_users` and `wp_posts` from staging.

___

Note:

* import command would not be altered, since it will import whatever was previously exported.
* blocked by #467
