### ISSUE TITLE
Wordmove excluding all files in upload, themes, plugins, mu-plugins, languages etc

### ISSUE THREAD

**Issue by matthewnw** [welaika/wordmove#479]
Wordmove seems to suddenly stop pushing and pulling anything other than `-w` and `-d`. 

Uploads, themes, plugins, mu-plugins, and languages respond with `./` and no files sent or received for version 3.1.1 and 3.1.0 which I've tested. (Didn't have any other versions installed)

However version 2.4.4 works perfectly with the same `movefile.yml`. Looking at the commands 

## Command output for Version 3.1.1 (not working)

    rsync --progress -e 'ssh -p 22 <user>@<host>' -rlpt --compress --omit-dir-times --delete --verbose --chmod\=Du\=rwX,Dgo\=rX,Fu\=rw,Fgo\=r --include /htdocs/wp-content/ --include /htdocs/wp-content/plugins/ --exclude ._\* --exclude .DS_Store --exclude .htaccess --exclude .env --exclude log --exclude provision --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .sass-cache/ --exclude node_modules/ --exclude composer.json --exclude composer.lock --exclude .editorconfig --exclude \*.md --exclude \*.scss --exclude \*.gulpfile --exclude \*.markdown --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude \*.sql --exclude Movefile --exclude movefile.yml --exclude php_codesniffer/ --exclude htdocs/wp-content/cache/ --exclude htdocs/wp-core/wp-content/ --exclude /\* --exclude /htdocs/wp-content/\* /srv/www/<website>/ :/home/<user>/public_html/websites/<website>/live

## Command output for Version 2.4.4 (working)

    rsync --progress -e 'ssh -p 22 <user>@<host>' -rlpt --compress --omit-dir-times --delete --verbose --chmod\=Du\=rwX,Dgo\=rX,Fu\=rw,Fgo\=r --exclude ._\* --exclude .DS_Store --exclude .htaccess --exclude .env --exclude log --exclude provision --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .sass-cache/ --exclude node_modules/ --exclude composer.json --exclude composer.lock --exclude .editorconfig --exclude \*.md --exclude \*.scss --exclude \*.gulpfile --exclude \*.markdown --exclude bin/ --exclude tmp/\* --exclude Gemfile\* --exclude \*.sql --exclude Movefile --exclude movefile.yml --exclude php_codesniffer/ --exclude htdocs/wp-content/cache/ --exclude htdocs/wp-core/wp-content/ /srv/www/<website>/htdocs/wp-content/uploads/ :/home/<user>/public_html/websites/<website>/live/htdocs/wp-content/uploads

## Anonymized movefile.yml: 

```yaml
global:
    sql_adapter: "wpcli"

local:
    vhost: "http://<vhost>"
    wordpress_path: "/srv/www/<website>"

    database:
        name: "<db_name>"
        user: "<db_user>"
        password: "<password>"
        host: "localhost"

    paths: # you can customize wordpress internal paths
        wp_content: "htdocs/wp-content"
        uploads:    "htdocs/wp-content/uploads"
        plugins:    "htdocs/wp-content/plugins"
        mu_plugins: "htdocs/wp-content/mu-plugins"
        themes:     "htdocs/wp-content/themes"
        languages:  "htdocs/wp-content/languages"

production:
    vhost: "https://<vhost>"
    wordpress_path: "/home/<user>/public_html/websites/<website>/live"

    database:
        name: "<db_name>"
        user: "<db_user>"
        password: "<password>"
        host: "localhost"
        
    exclude:
        - "._*"
        - ".DS_Store"
        - ".htaccess"
        - ".env"
        - "log"
        - "provision"
        - ".git/"
        - ".github/"
        - ".gitignore"
        - ".sass-cache/"
        - "node_modules/"
        - "composer.json"
        - "composer.lock"
        - ".editorconfig"
        - "*.md"
        - "*.scss"
        - "*.gulpfile"
        - "*.markdown"
        - "bin/"
        - "tmp/*"
        - "Gemfile*"
        - "*.sql"
        - "Movefile"
        - "movefile.yml"
        - "php_codesniffer/"
        - "htdocs/wp-content/cache/"
        - "htdocs/wp-core/wp-content/"

    paths: # you can customize wordpress internal paths
        wp_content: "htdocs/wp-content"
        uploads:    "htdocs/wp-content/uploads"
        plugins:    "htdocs/wp-content/plugins"
        mu_plugins: "htdocs/wp-content/mu-plugins"
        themes:     "htdocs/wp-content/themes"
        languages:  "htdocs/wp-content/languages"

    ssh:
       host: "<host>"
       user: "<user>"
       port: 22 # Port is optional (Default: 22)
       rsync_options: "--verbose --chmod=Du=rwX,Dgo=rX,Fu=rw,Fgo=r" 
```

It looks like the the `--exclude /\*` in the 3.1.1 version are blanket ignoring everything for some reason? We've also been using post 3.0.0 for some time with no problems, I don't understand why it's suddenly stopped working. 

This is the reproducable for multiple projects with varying setups (all previously working with wordmove 3.0 I believe) and also on different devices (Linux Mint 17,18 and Mac OSX) all running Vagrant VVV 2.1.0.

**Comment by matthewnw** [comment]
For ease of anyone testing this with different versions, I can run the following commands for the same movefile:

    wordmove _3.1.1_ pull -e production -u # DOESN'T WORK

    wordmove _2.4.4_ pull -e production -u # DOES WORK

**Comment by pioneerskies** [comment]
I consider this one a urgent bug; thanks for submitting your report.

I think the quite radically new approach introduced by 3.1.x about the `rsync` command generation is somewhat ignoring custom directories settings in

```yml
paths: # you can customize wordpress internal paths
        wp_content: "htdocs/wp-content"
        uploads:    "htdocs/wp-content/uploads"
        plugins:    "htdocs/wp-content/plugins"
        mu_plugins: "htdocs/wp-content/mu-plugins"
        themes:     "htdocs/wp-content/themes"
        languages:  "htdocs/wp-content/languages"
```

I'll investigate this evening or tomorrow morning and I'll keep you updated obviously.

Meanwhile 3.0 should work flawlessly in your scenario.
