### ISSUE TITLE
Movefile case sensitivity on *nix systems

### ISSUE THREAD

**Issue by rbndelrio** [welaika/wordmove#483]
I was trying out `docker-wordmove` earlier and came across a few roadblocks along the way (I'll make an issue for the others in that repo). I have a `docker-compose.yml` that looks largely the same as that Medium article about simonbland/docker-wordmove:

```yaml
...
  wordmove:
    image: welaika/wordmove
    depends_on:
      - wordpress
    restart: always
    working_dir: /var/www/html/
    volumes:
      - ./wp:/var/www/html
      - ./themes:/var/www/html/wp-content/themes/
      - ./config/.env:/var/www/html/.env
      - ./config/movefile.yml:/var/www/html/movefile.yml
      - ~/.ssh:/home/wordmove/.ssh:ro
    tty: true
...
```

When trying to pull, I got an error (`undefined method 'deep_symbolize_keys!' for nil:NilClass (NoMethodError)`) that was directed at line 26 of movefile.rb.

Looking at [the fetch method
](https://github.com/welaika/wordmove/blob/master/lib/wordmove/movefile.rb#L11-L27), I'm pretty sure it has to do with how the `File` and `Dir` classes treat case-sensitivity on *nix filesystems as it was able to find my movefile but `found` evaluated to  `/var/www/html/Movefile.yml`

I was able to skip this roadblock by amending `docker-compose.yml`:

```yaml
volumes:
  - ./config/movefile.yml:/var/www/html/Movefile
```

Again, Ruby (and i/o stuff like this) is a little out of my spectrum, but my Google-fu suggests `File::FNM_CASEFOLD` can make Dir.glob calls case-insensitive, so lines 12-16 could be reworked to utilize that?
