### ISSUE TITLE
Exclude & FTP

### ISSUE THREAD

**Issue by tameroski** [welaika/wordmove#486]
Is the "exclude" feature supposed to work with an FTP push ?

.git directory should be excluded but is still transfered anyway 😞 

command : `wordmove push -e production -t`

configuration : 

```
...
production:
    vhost: http://www.xxxxxxxx.com
    wordpress_path: /www

    database:
        name: xxxxx
        user: xxxxx
        password: xxxxxx
        host: xxxxxxxx

    exclude:
        - '.git'
        - 'wp-content/themes/xxx/.git'
        - 'xxx/.git'

    ftp:
        user: xxxxxx
        host: xxxxxx

    hooks:
        push:
            before:
                local:
                    - 'cd wp-content/themes/xxx && npm install && npm run prod && git commit --amend --no-edit && git push -f origin master && cd ../../..'
```

PS : it's working just fine with the same configuration on another environnement using SSH
