### ISSUE TITLE
Not excluding file when pushing theme through FTP

### ISSUE THREAD

**Issue by tameroski** [welaika/wordmove#509]
Hi,

Im pushing my theme through FTP, and ignored folders keep being transfered. There might be something wrong in my movefile.yml but i can't figure it out :

```yml
global:
    sql_adapter: wpcli

local:
    vhost: http://localhost:80
    wordpress_path: "<%= Dir.pwd %>" 

staging:
    vhost: xxx
    wordpress_path: aaa
    wordpress_absolute_path: /home/user/aaa

    ftp:
        host: xxx
        user: xxx

    exclude:
        - 'wp-content/themes/bbbb/src/' # this keeps being transfered

...
```

I simply run : `wordmove push -e staging -t`

Here is some output : 

```
   remote | put_directory: /Users/MyUser/dev/wp-content/themes aaa/wp-content/themes src wp-content/themes/bbbb/src/
    ℹ️  info | lftp -c 'set ftp:list-options -a; set ftp:passive-mode false; set cmd:fail-exit true; open -p 21 ftp://xxx@xxx; find -d 1 aaa/wp-content/themes || mkdir -p aaa/wp-content/themes; lcd /Users/MyUser/dev/wp-content/themes; cd aaa/wp-content/themes; mirror --delete --use-cache --verbose --no-perms --allow-suid --no-umask --parallel=5 --reverse --dereference --exclude-glob src --exclude-glob wp-content/themes/bbbb/src/'
Password: 
aaa/wp-content/themes/                                           
Removing old file `bbbb/src/test.txt'                           
Transferring file `bbbb/src/test.txt'
```

Wordmove 4.0.0
LFTP 4.8.4

Any idea ?
