### ISSUE TITLE
Database Pull URL Rewrite is breaking

### ISSUE THREAD

**Issue by sha-one** [welaika/wordmove#515]
I've encountered an issue where I run a DB Pull and the URL is not being rewritten correctly, for example...

```
local:
  vhost: "http://domainname.local"
  wordpress_path: "/Users/shaone/Local\ Sites/domainname/app/public"

staging:
  vhost: "http://domain-name.domain.com"
  wordpress_path: "/private/git"
```

What I get in the DB after pulling to local is: **http://domain-name.loc** rather than **http://domainname.local** which is what I'm expecting.

I've never encountered this problem before, any ideas?
Note: staging is setup as a subdomain (I don't have control over this) and it is a single-site install

Thanks!
