### ISSUE TITLE
Pushing to server breaks URLs

### ISSUE THREAD

**Issue by humblecoder** [welaika/wordmove#517]
Pushing my local site breaks URLs on the remote site.  For example, www.mysite.com still works, but all  non-homepage links are broken (e.g. www.mysite.com/blog).  The fix appears to be to log into the remote wp-admin and simply go to SETTINGS and select SAVE.  At that point, whatever can't be found is suddenly available again.  Why is this happening, and how do I automate the fix?

**Comment by pioneerskies** [comment]
Hello there @humblecoder ! Sorry to be such late.

I'm also sorry for having no idea at all about why this is happening to you. About automating the fix it depends on what saving your settings is actually triggering...one idea is to force permalinks regeneration. You can achieve this if you have WP-CLI remotely installed thanks to Wordmove's hooks:

```yml
your_remote_section:
  hooks:
    push:
      after:
        remote:
          - `wp rewrite flush`
```
