### ISSUE TITLE
Errorcode 1 with gzip of database dump.sql during database pull

### ISSUE THREAD

**Issue by mechdog** [welaika/wordmove#528]
Having an issue with pulling the database from a WPEngine site with ssh access. The dump.sql file is created but the gzip command seems to error out. If I copy and paste the same gzip command on the remote server myself it runs fine. 
 
```
wordmove pull -d

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --port=8889 --user=[blanked] --password=[blanked] --result-file="/sites/cooper2019/wp-content/local-backup-1559245811.sql" cooper2019
mysqldump: [Warning] Using a password on the command line interface can be insecure.
    local | gzip -9 -f "/sites/cooper2019/wp-content/local-backup-1559245811.sql"
   remote | mysqldump --host=127.0.0.1 --user=[blanked] --password=[blanked] --result-file="/home/wpe-user/sites/cooper2019/wp-content/dump.sql" wp_cooper2019
   remote | gzip -9 -f "/home/wpe-user/sites/cooper2019/wp-content/dump.sql"
/Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:70:in `remote_run': Error code 1 returned by command "gzip -9 -f "/home/wpe-user/sites/cooper2019/wp-content/dump.sql"":  (Wordmove::ShellCommandError)
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:80:in `download_remote_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:34:in `adapt_remote_db!'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:48:in `pull_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:79:in `block in pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:78:in `pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `load'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `<main>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
```

movefile.yml:
```
global:
  sql_adapter: wpcli

local:
  vhost: "http://cooper2019.dev"
  wordpress_path: "/sites/cooper2019" # use an absolute path here

  database:
    name: "cooper2019"
    user: "[blanked]"
    password: "[blanked]"
    host: "127.0.0.1"
    port: "8889"

production:
  vhost: "http://cooper2019.wpengine.com"
  wordpress_path: "/home/wpe-user/sites/cooper2019" # use an absolute path here

  database:
    name: "wp_cooper2019"
    user: "[blanked]"
    password: "[blanked]"
    host: "127.0.0.1"
    # port: "3308" # Use just in case you have exotic server config

  ssh:
    host: "[asite].ssh.wpengine.net"
    user: "[ssh_user]"
 

  exclude:
    - '.git/'
    - '.gitignore'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'
```
If I ssh into the server and run:
```
gzip -9 -f "/home/wpe-user/sites/cooper2019/wp-content/dump.sql"
```
it runs fine. The dump.sql file is created on the remote server and has the database data in it as well, so it really appears to be the gzip command. Not sure if there is a way for me to get a more verbose error from it some how when wordmove runs, was hoping the manually runned command would give an error I could grab to help.

```
Using Mac OS 10.14.4
rvm
ruby version 2.4.6
```

Really hope I'm just doing some thing dumb other then not wanting to take up people's time for that...
