### ISSUE TITLE
Doctor doesn't know Vhost can be stored in .env file.

### ISSUE THREAD

**Issue by Gadgitmatic** [welaika/wordmove#535]
I've stored all my personally identifying information in a .env file rather than the movefile itself. This works great! Though, when running `wordmove doctor` it gives the following error:

```
 ▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Validating movefile section: global ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | Formal validation passed

▬▬ Validating movefile section: local ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✅  success | Formal validation passed

▬▬ Validating movefile section: production ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ❌  error | [/vhost] '': not matched to pattern /^https?:\/\//.

▬▬ Validating movefile section: stg ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ❌  error | [/vhost] '': not matched to pattern /^https?:\/\//.
 ```

This is somewhat of a false-flag since the vhost is correct, just that it's found in the .env file not the movefile.

This is what my movefile looks like

```  
production:
    vhost: "<%= ENV['Pvhost'] %>"
    wordpress_path: "<%= ENV['Ppath'] %>"

    database:
        name: "<%= ENV['PDB'] %>"
        user: "<%= ENV['USER'] %>"
        password: "<%= ENV['PASS'] %>"
        host: "localhost"
    ssh:
        host: "<%= ENV['SSH'] %>"

  stg:
    vhost: "<%= ENV['Svhost'] %>"
    wordpress_path: "<%= ENV['Spath'] %>"

    database:
        name: "<%= ENV['SDB'] %>"
        user: "<%= ENV['USER'] %>"
        password: "<%= ENV['PASS'] %>"
        host: "localhost"
    ssh:
        host: "<%= ENV['SSH'] %>" 
```
