### ISSUE TITLE
rsync and symbolic links

### ISSUE THREAD

**Issue by nghh** [welaika/wordmove#547]
Hi, 
i'm developing  local composer libraries witch are symlinked in composer.json

```json
"repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        },
        {
            "type": "path",
            "url": "~/development/composer/nghh/phplibrary"
        }
    ]
```

When i make a push, rsync won't follow those symlinks in the vendor directory. 
If i'm right, it's because wordmove preforms rsync with the -l rather the -L flag.

Is there a way that I can perform a push that follows the symbolic links?

Thank you!

**Comment by nghh** [comment]
ohman, this was easy. if anyone else run into this problem:

Just add **rsync_options: "--copy-links"** to your wordmove file:

```yaml
  ssh:
    host: 123.123.123.123
    user: username
    rsync_options: "--copy-links"
```
Cheers
