### ISSUE TITLE
Couldn't execute 'SHOW VARIABLES LIKE 'gtid\_mode'': Table 'performance_schema.session_variables' doesn't exist (1146)

### ISSUE THREAD

**Issue by nailbrain** [welaika/wordmove#549]
Hi, I'm having problems pulling a database from a live server to a local environment.

Has anyone experienced a similar issue?

```
 local | mysqldump --host=127.0.0.1 --port=8889 --user=root --password=root --result-file="/Users/brettgolding/Google Drive/htdocs/ridgeline/wp-content/local-backup-1573451564.sql" --hex-blob ridgeline-staging
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute 'SHOW VARIABLES LIKE 'gtid\_mode'': Table 'performance_schema.session_variables' doesn't exist (1146)
/Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/base.rb:93:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/base.rb:179:in `save_local_db'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/default_sql_adapter.rb:23:in `backup_local_db!'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:47:in `pull_db'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/cli.rb:79:in `block in pull'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/lib/wordmove/cli.rb:78:in `pull'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/wordmove:23:in `load'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/wordmove:23:in `<main>'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brettgolding/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
BrettMac:ridgeline brettgolding$ 
```

Here is a copy of my config file:

```
global:
  sql_adapter: default

local:
  vhost: http://localhost:8888/ridgeline
  wordpress_path: /Users/brettgolding/Google Drive/htdocs/ridgeline # use an absolute path here

  database:
    name: ridgeline-staging
    user: root
    password: "root" # could be blank, so always use quotes around
    host: 127.0.0.1
    port: "8889" # Use just in case you have exotic server config
    mysqldump_options: --hex-blob

production:
  vhost: https://website.com
  wordpress_path: /home1/ttsdrbmy/public_html/website # use an absolute path here

  database:
    name: database
    user: user
    password: password
    host: localhost
    # port: 3308 # Use just in case you have exotic server config
    mysqldump_options: --hex-blob
    # mysql_options: '--protocol=TCP' # mysql command is used to import db

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - ".htaccess"
    - 'wp-content/*.sql.gz'
    - '*.orig'

  ssh:
    host: ip address
    user: username
```
