### ISSUE TITLE
[/forbid] key 'forbid:' is undefined.

### ISSUE THREAD

**Issue by karneaud** [welaika/wordmove#559]
I have the following configuration in my movefile

```
production:
  forbid:
    push:
      db: true
      plugins: true
      themes: true
      languages: false
      uploads: true
      mu-plugins: false
    pull:
      db: true
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu-plugins: false
```

When executing the `wordmove doctor` command...I get the following output

>  ▬▬ Validating movefile section: production ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    ✗ error | [/forbid] key 'forbid:' is undefined.

What does it mean?
