### ISSUE TITLE
Error in database replacing wordpress_path

### ISSUE THREAD

**Issue by marekmaurizio** [welaika/wordmove#577]
```
local:
  vhost: https://www.trevicoliseum.local
  wordpress_path: /Users/marek/Projects/Larin/trevicoliseum-it/trevicoliseum-it # use an absolute path here

staging:
  vhost: https://staging.trevicoliseum.it
  wordpress_path: /staging.trevicoliseum.it # use an absolute path here
```

This is my setup. The first database replacement works, then the second one wrecks havoc and put the wordpress_path inside all urls. Why the path gets replaced? Is it possible to skip?
