### ISSUE TITLE
How wordmove replaces URLs? 

### ISSUE THREAD

**Issue by rodosskiand** [welaika/wordmove#578]
**Describe the bug**
How wordmove replaces URLs? 
Afte
```
wordmove pull -all 
```

command on localhost stays redirection to remote url. But after command:

```
wp search-replace 'site.com' 'localhost'  
```

all its ok

And how in wordmove realized replacing urls?

**movefile.yml**

```
global:
  sql_adapter: default

local:
  vhost: "http://localhost"
  wordpress_path: "/var/www/html"
  database:
    name: "wordpress"
    user: "wordpress"
    password: "secret"
    host: "database"
    mysqldump_options: "--hex-blob"

development:
  vhost: "https://host.com"
  wordpress_path: "/var/www/path"

  database:
    name: "name"
    user: "user"
    password: "fhbitstupassdioscom"
    host: "127.0.0.1"
    port: "3306"
    mysqldump_options: "--hex-blob"


  ssh:
    host: "host.com"
    user: "user"
    password: "pass"
    port: "22"
    rsync_options: "--verbose -e 'sshpass -p 'pass' ssh -o StrictHostKeyChecking=no -p 22 user@host.com'"
```

**Environment (please complete the following information):**
- OS: Ubuntu 18
- Wordmove: welaika/wordmove:alpine
