### ISSUE TITLE
WpCli not being set as SqlAdapter, leading to invalid byte sequence in US-ASCII on db pull

### ISSUE THREAD

**Issue by B-Stewart** [welaika/wordmove#581]
**Describe the bug**
It seems setting wpcli as the sql_adapter isn't applying as I'm getting

`/usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:45:in  `gsub!': invalid byte sequence in US-ASCII (ArgumentError) `

while attempting to pull the database. I read the docs here https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db and attempted to swap to wpcli, however I'm still getting this error even with the config set.

**Wordmove command**
`wordmove pull -e production --all`

**Expected behavior**
As I understand it, the /default.rb file shouldn't be called, and instead should use the wpcli.rb file in that directory? However, I'm not sure why my config isn't applying that adapter, therefore the default one is being used and the invalid byte sequence is throwing an error.

**movefile.yml**
```
global:
  sql_adapter: "wpcli"

local:
  vhost: "http://localhost:<%= ENV['LOCAL_SERVER_PORT'] %>"
  wordpress_path: "/var/www/html/"
  database:
    name: "wordpress"
    user: "root"
    password: "wordpress"
    host: "database"
    mysqldump_options: "--hex-blob"

production:
  vhost: "<%= ENV['PRODUCTION_URL'] %>"
  wordpress_path: "<%= ENV['PRODUCTION_DIR_PATH'] %>"
  wordpress_absolute_path: "<%= ENV['PRODUCTION_ABS_DIR_PATH'] %>" #Omit this for SSH

  database:
    name: "<%= ENV['PRODUCTION_DB_NAME'] %>"
    user: "<%= ENV['PRODUCTION_DB_USER'] %>"
    password: "<%= ENV['PRODUCTION_DB_PASSWORD'] %>"
    host: "<%= ENV['PRODUCTION_DB_HOST'] %>"
    port: "<%= ENV['PRODUCTION_DB_PORT'] %>"
    mysqldump_options: "--hex-blob"

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'
    - 'wp-content/uploads/backwpup*/*'
    - '.htaccess'
    - '.idea/'

  ftp:
    host: "<%= ENV['PRODUCTION_FTP_HOST'] %>"
    user: "<%= ENV['PRODUCTION_FTP_USER'] %>"
    password: "<%= ENV['PRODUCTION_FTP_PASS'] %>"
    port: "<%= ENV['PRODUCTION_FTP_PORT'] %>"
    passive: true
    scheme: "ftp"

  forbid:
    push:
      db: true
      plugins: true
      themes: true
      languages: true
      uploads: true
      mu-plugins: true
```

**Exception/trace**
Paste (removing personal data) the entire trace of error/exception you encountered, if any
```
▬▬ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

    local | mysqldump --host=[secret] --user=root --password=[secret] --result-file="[secret]wp-content[secret]local-backup-1580593012.sql" --hex-blob [secret]

   remote | write [secret]wp-content[secret]dump.php

    local | download [secret][secret]wp-content[secret]dump.php?shared_key=376c3546399852c35ffc0ce2a8dab0da522af29d100f828a1f4f8967211a5e7f8611ab7d356dae87 > [secret]wp-content[secret]dump.sql

   remote | delete: [secret]wp-content[secret]dump.php

   remote | delete: [secret]wp-content[secret]dump.mysql

    local | Adapt dump
Traceback (most recent call last):
        18: from /usr/local/bundle/bin/wordmove:23:in `<main>'
        17: from /usr/local/bundle/bin/wordmove:23:in `load'
        16: from /usr/local/bundle/gems/wordmove-5.0.2/exe/wordmove:6:in `<top (required)>'
        15: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/cli.rb:91:in `pull'
        10: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/cli.rb:39:in `handle_options'
         9: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/cli.rb:39:in `each'
         8: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/cli.rb:40:in `block in handle_options'
         7: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/cli.rb:92:in `block in pull'
         6: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/deployer/ftp.rb:47:in `pull_db'
         5: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/deployer/ftp.rb:156:in `adapt_sql'
         4: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:18:in `adapt!'
         3: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:26:in `replace_vhost!'
         2: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:38:in `replace_field!'
         1: from /usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:45:in `serialized_replace!'
/usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb:45:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
```
**Environment (please complete the following information):**
- OS: Windows (I'm `exec` into the docker image welaika/wordmove)
- Ruby: (`ruby --version`) `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]` from the img
- Wordmove: (`wordmove --version`) `5.0.2` from the img

**Doctor**
* [x] `wordmove doctor` is all green

(If it is not, report the error you got.)
Only issue is wp-cli says success but Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under. (Probably because docker?)
