### ISSUE TITLE
Local backup of database with views fails

### ISSUE THREAD

**Issue by Korkey128k** [welaika/wordmove#583]
**Describe the bug**
When pulling a database with a view, the local backup fails to run because the definer (remote user) does not exist;  
`mysqldump: Got error: 1449: "The user specified as a definer ('{remote_user}'@'{remote_host}') does not exist" when using LOCK TABLES`

**Wordmove command**
`wordmove pull -d -e staging`

**Expected behavior**
The local database successfully backs up.

**movefile.yml**
```yaml
global:
  sql_adapter: wpcli

local:
  vhost: #######
  wordpress_path: #######

  database:
    name: #######
    user: #######
    password: #######
    host: localhost

staging:
  vhost: #######
  wordpress_path: #######

  database:
    name: #######
    user: #######
    password: #######
    host: localhost

  exclude:
    - '.git/'
    - '.gitignore'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'
    - 'dev.log'

  ssh:
    host: #######
    user: #######
```

**Exception/trace**
```
local | mysqldump --host=[secret] --user=[secret] --password=[secret] --result-file="[secret]/wp-content/local-backup-1580911741.sql" #########
mysqldump: Got error: 1449: "The user specified as a definer ('{remote_user}'@'{remote_host}') does not exist" when using LOCK TABLES
Traceback (most recent call last):
  17: from #####/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
  16: from #####/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
  15: from #####/gems/ruby-2.6.3/bin/wordmove:23:in `<main>'
  14: from #####/gems/ruby-2.6.3/bin/wordmove:23:in `load'
  13: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/exe/wordmove:6:in `<top (required)>'
  12: from #####/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  11: from #####/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  10: from #####/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
   9: from #####/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
   8: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/cli.rb:91:in `pull'
   7: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/cli.rb:39:in `handle_options'
   6: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/cli.rb:39:in `each'
   5: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/cli.rb:40:in `block in handle_options'
   4: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/cli.rb:92:in `block in pull'
   3: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/deployer/ssh.rb:47:in `pull_db'
   2: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:29:in `backup_local_db!'
   1: from #####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/deployer/base.rb:183:in `save_local_db'
#####/gems/ruby-2.6.3/gems/wordmove-5.0.2/lib/wordmove/deployer/base.rb:95:in `run': Return code reports an error (Wordmove::ShellCommandError)
```

**Environment (please complete the following information):**
- OS: MacOS 10.15.2
- Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
- Wordmove: 5.0.2

**Doctor**
* [x] `wordmove doctor` is all green
