### ISSUE TITLE
Bedrock Installation Paths with WP-CLI Adapter

### ISSUE THREAD

**Issue by maiorano84** [welaika/wordmove#590]
Using the latest version of Wordmove with [Bedrock](https://roots.io/bedrock/), there appears to be a strange conflict between how Wordmove resolves its paths and how paths are being sent to WP CLI to determine the Core Wordpress installation.

After some experimentation, I've narrowed down this behavior to a few scenarios specific to Bedrock that might be worth looking into.

For reference, the basic directory structure of Bedrock can be represented as follows:

```
.
├── config
│   ├── environments
│   └── application.php
├── web
│   ├── app
│   │   ├── plugins
│   │   ├── themes
│   │   └── uploads
│   ├── wp
│   │   ├── wp-admin
│   │   ├── wp-content
│   │   └── wp-includes
│   └── wp-config.php
├── composer.json
├── wp-cli.yml
└── .env
```

## Scenario 1 - Uploads Push/Pull
All commands are executed using `wordmove pull -e dev -u`

_Configuration Test 1: Absolute paths and Wordpress root_ - **Fails**
When using this type of configuration against a Bedrock installation, no uploads are recognized and the command completes **without** downloading images.
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web/wp

  paths:
    uploads: "/var/www/html/web/app/uploads"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web/wp

  paths:
    uploads: "/path/to/root/web/app/uploads"
```

_Configuration Test 2: Relative paths and Wordpress root_ - **Fails**
A similar setup using relative paths also completes **without** downloading images:
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web/wp

  paths:
    uploads: "../app/uploads"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web/wp

  paths:
    uploads: "../app/uploads"
```

_Configuration Test 3: Relative paths and Document root_ - **Succeeds**
When pointing the **wordpress_path** one level back to Document root however, the following setup succeeds **and all images are downloaded without issue**
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web # Not the Wordpress path

  paths:
    uploads: "app/uploads"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web # Not the Wordpress path

  paths:
    uploads: "app/uploads"
```

## Scenario 2 - Database Push/Pull
All commands are executed using `wordmove pull -e dev -d`

_Configuration Test 1: Absolute paths and Wordpress root_ - **Fails**
Ordinarily I would expect this to succeed, but the SQL Dump execution fails due to the Wordpress path being concatenated with the wp_content path, resulting in an error:

**_Can't create/write to file '/var/www/html/web/wp/var/www/html/web/wp/wp-content/local-backup-1587063366.sql'_**
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web/wp

  paths:
    wp_content: "/var/www/html/web/wp/wp-content"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web/wp

  paths:
    wp_content: "/path/to/root/web/wp/wp-content"
```

_Configuration Test 2: Relative paths and Wordpress root_ - **Succeeds**
This command succeeds without issue. It is understood that the wp_content path can be left out in this case, as this is the default value of this path.
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web/wp

  paths:
    wp_content: "wp-content"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web/wp

  paths:
    wp_content: "wp-content"
```

_Configuration Test 3: Relative paths and Document root_ - **Fails**
This is where SQL Dump will succeed, but WP CLI fails with the following error:

**Error: This does not seem to be a WordPress installation.  
Pass --path=`path/to/wordpress` or run `wp core download`**
```
local:
  vhost: http://localhost
  wordpress_path: /var/www/html/web

  paths:
    wp_content: "wp/wp-content"

dev:
  vhost: https://dev.domain.com
  wordpress_path: /path/to/root/web

  paths:
    wp_content: "wp/wp-content"
```

## The Problem
Running either `wordmove pull -e dev -d` or `wordmove pull -e dev -u` in isolation each has a working configuration when WP CLI is the selected adapter.

Unfortunately, no combination of settings would allow us to run the following command with success:

`wordmove pull -e dev -du`

Absolute paths against Wordpress root fails in both scenarios. 
Relative paths against Wordpress root fails in Scenario 1 and succeeds in Scenario 2 
Relative paths against Document root succeeds in Scenario 1 and fails in Scenario 2 

The only way around this at the moment is to use the `default` adapter and use relative paths against Document root. I would prefer to avoid this if I can.

## The Solution
I'm not sure how paths are being resolved, but the SQL Dump output path should probably have a check to determine whether or not absolute vs relative is used, and concatenate only when relative paths are specified.

When it comes to path resolution for rsync, neither absolute paths nor relative paths appear to be honored properly if the **wordpress_path** setting is one level deeper than the rest of the paths. I'm not even sure that **wordpress_path** should even have a role in determining the path for uploads, themes, plugins, or languages, but I can't be certain since I don't know what code is driving this behavior.

Lastly, it looks as if WP CLI will fail no matter what if **wordpress_path** is not pointing to a Wordpress instance. That means that even if we have a wp-cli.yml file in our project root to tell it where Wordpress actually is, it's being ignored in favor of the --path flag and we still see the **This does not seem to be a WordPress installation** error.

Let me know if any of this is unclear or if you need me to test anything further. Myself and my team have been using Wordmove for years and love everything about it!

**Environment**
- OS: Alpine Linux (Docker)
- Ruby: 2.7.1p83
- Wordmove: 5.0.2
