### ISSUE TITLE
Rsync custom folder

### ISSUE THREAD

**Issue by huraji** [welaika/wordmove#592]
Hello there,

trying to rsync a custom folder, while pushing as following:

```
push:
      before:
        - command: 'wp export --post_type=elementor_library,product,wpcf7_contact_form,page  --dir=wp-content/exports'
          where: local
        - command: 'rsync -a --delete wp-content/exports/ user@host:public_html/wp-content/exports/'
          where: local
      after:
        - command: 'wp search-replace "http://localhost" "http://host" --skip-columns=guid --skip-plugins'
          where: remote
        - command: 'wp import public_html/wp-content/exports'
          where: remote
```

As you can see the idea is to export specific data in a safe way, without operating directly on mysql. I get this error:

`rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]`

I guess because I'm already in the rsync data stream. 
Do you know any workaround or alternative solution for this approach?

Thanks.

**Comment by pioneerskies** [comment]
Hi,

from what I can see that could be rsync not finding the folders. I'd try something like

```yml
push:
      before:
        - command: 'wp export --post_type=elementor_library,product,wpcf7_contact_form,page  --dir=wp-content/exports'
          where: local
        - command: 'rsync -a --delete wp-content/exports/ user@host:wp-content/exports/'
          where: local
      after:
        - command: 'wp search-replace "http://localhost" "http://host" --skip-columns=guid --skip-plugins'
          where: remote
        - command: 'wp import wp-content/exports'
          where: remote
```

My deduction is that `public_html` folder is 1 level upper your wordpress dir, but since commands are invoked from inside the wordpress dir rsync can't find the that folder.

Does it worth a try?
