### ISSUE TITLE
Can't SSH into Local by Flywheel

### ISSUE THREAD

**Issue by alexanderkladov** [welaika/wordmove#593]
**Describe the bug**
I am trying to use WordMove to quickly migrate all of my local MAMP sites into my local [Local by Flywheel](https://localwp.com/), but I can't get it to work. Local uses docker, so I assumed I could treat it as a "remote server" and push my MAMP sites into it using WordMove. But seems like it might not be as simple as I thought it was gonna be..

First of all, since I can't easily tell WordMove how to SSH into Local/docker, I created the following `~/.ssh/config` entry for my test site:
```
Host local_by_flywheel_test
	HostName 192.168.95.100
	User docker
	IdentityFile ~/.docker/machine/machines/local-by-flywheel/id_rsa
	RequestTTY force
	RemoteCommand docker exec -it af8296b4e0e1b228856fcd0bd5d532fd1628df6acda46323e3c701e81a537832 /bin/bash
```
The first 3 lines log into the Local "server" instance and the last 2 lines force it to jump into my desired docker container right away.

It works like a charm via simple `ssh local_by_flywheel_test` directly from my Terminal. It jumps right into the docker container and I can run whatever I need right away, like `wp`, `myslq`, `mysqldump` etc. Basically it's replicating the SSH login behaviour used by Local's UI (i.e. right click on site and then "Open Site SSH").

I thought this was gonna be enough to make WordMove happy, since I could use that pre-configured host in my `movefile.yml`. But when I run a WordMove `push`, I get a `Cannot execute command-line and remote command` error.

Is that a bug or am I just doing what I shouldn't be doing? :) I know this is a weird setup, since I am moving from local to local. But docker is technically not local, so I thought it was gonna work.

**movefile.yml**
This is what some of my Movefile looks like:
```yml
###################
# Local by Flywheel
###################
<% env_name       = "local_by_flywheel_test" %>
<% vhost          = "https://local_by_flywheel.test" %>
<% wordpress_path = "app/public" %>
<% db_host        = "localhost" %>
<% db_name        = "local" %>
<% db_user        = "root" %>
<% db_pass        = "root" %>
<% ssh_host       = "local_by_flywheel_test" %>
<%= env_name %>: &env_core
  vhost: <%= vhost %>
  wordpress_path: <%= wordpress_path %>
  <<: *defaults
  database:
    host: "<%= db_host %>"
    name: "<%= db_name %>"
    user: "<%= db_user %>"
    password: "<%= db_pass %>"
    port: "<%= db_port %>"
  ssh:
    host: "<%= ssh_host %>"
```

**Exception/trace**
```shell
Alexanders-MacBook-Pro-5:test alexanderkladov$ wordmove push -e local_by_flywheel_test -ts

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pushing Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Applications/MAMP/htdocs/dev/test app/public /wp-content/* ~* ._* .DS_Store .DS_Store? .Spotlight-V100 .Trashes ehthumbs.db Thumbs.db Gemfile* Movefile movefile movefile.yml movefile.yaml composer.phar wp-config-*.php sitemap.xml sitemap.xml.gz *.sublime-project *.sublime-workspace *.komodoproject *.orig wp-content/plugins/hello.php wp-content/*.sql.gz wp-content/*.sql database-versions/ wp-content/advanced-cache.php wp-content/wp-cache-config.php config/wp-config.*.db_password.php config/.env .git/ .gitignore .editorconfig .vscode icon.jpg .sass-cache/ node_modules/ bin/ tmp/* wp-content/blogs.dir/ wp-content/themes/twenty*/ wp-snapshots/ wp-content/updraft/ wp-content/backup-db/ wp-content/backups/ backups/ wp-content/uploads/backwpup*/ backwpup* wp-content/uploads/*backupbuddy* wp-content/cache/ /* /wp-content/themes/ /wp-content/
    ℹ️  info | rsync --progress -e 'ssh local_by_flywheel_test' -rlpt --compress --omit-dir-times --delete --dry-run --include /wp-content/themes/ --include /wp-content/ --exclude /wp-content/\* --exclude \~\* --exclude ._\* --exclude .DS_Store --exclude .DS_Store\? --exclude .Spotlight-V100 --exclude .Trashes --exclude ehthumbs.db --exclude Thumbs.db --exclude Gemfile\* --exclude Movefile --exclude movefile --exclude movefile.yml --exclude movefile.yaml --exclude composer.phar --exclude wp-config-\*.php --exclude sitemap.xml --exclude sitemap.xml.gz --exclude \*.sublime-project --exclude \*.sublime-workspace --exclude \*.komodoproject --exclude \*.orig --exclude wp-content/plugins/hello.php --exclude wp-content/\*.sql.gz --exclude wp-content/\*.sql --exclude database-versions/ --exclude wp-content/advanced-cache.php --exclude wp-content/wp-cache-config.php --exclude config/wp-config.\*.db_password.php --exclude config/.env --exclude .git/ --exclude .gitignore --exclude .editorconfig --exclude .vscode --exclude icon.jpg --exclude .sass-cache/ --exclude node_modules/ --exclude bin/ --exclude tmp/\* --exclude wp-content/blogs.dir/ --exclude wp-content/themes/twenty\*/ --exclude wp-snapshots/ --exclude wp-content/updraft/ --exclude wp-content/backup-db/ --exclude wp-content/backups/ --exclude backups/ --exclude wp-content/uploads/backwpup\*/ --exclude backwpup\* --exclude wp-content/uploads/\*backupbuddy\* --exclude wp-content/cache/ --exclude /\* /Applications/MAMP/htdocs/dev/test/ :app/public
Cannot execute command-line and remote command.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]
```

**Environment:**
- OS: macOS Mojave v10.14.6 (18G4032)
- Ruby: ruby 2.6.0dev (2018-04-12 trunk 63136) [x86_64-darwin17]
- Wordmove: 3.2.2

**Comment by pioneerskies** [comment]
Hm. Too exotic even to troubleshoot for me. But that's not a Wordmove's exception, but an rsync's error. Are you sure to have rsync installed inside the docker image?

**Comment by alexanderkladov** [comment]
I didn't think it was that weird.. :) I just have MAMP & Local by Flywheel (the older version, since new v5 Local "Lightning" doesn't have Apache). I just got sick of MAMP being a slow, so was trying to move everything over in the most painless way possible from one to another.

The only weird thing I'm doing is that I am trying to move from one local instance to another, which obviously wouldn't be possible using Wordmove. But Local is not technically "local" and has it's own SSH, DB & everything, so I was hoping that wasn't gonna be a problem.

And yes, Local comes with `rsync`, so I don't think that's the problem. It's these 2 lines of the `~/.ssh/config`  that are causing the error:
```
	RequestTTY force
	RemoteCommand docker exec -it af8296b4e0e1b228856fcd0bd5d532fd1628df6acda46323e3c701e81a537832 /bin/bash
```

If I remove them, I can at least connect to Local. But I am in any particular docker container, so that doesn't work - I can't use DB functions that way. I need to use those 2 lines to jump into the associated docker container ID (**af8296b4e0e1b228856fcd0bd5d532fd1628df6acda46323e3c701e81a537832**), the moment I SSH into local (before doing anything else), in order to `mysqldump` the DB.

**Comment by pioneerskies** [comment]
I didn't want to objectively judge your setup 😂 , I'm just saying it's weird for me and my experience 😉 

And it comes up to be a little weired for `rsync` too. I'd confirm it's not a bug in Wordmove. But generally I'm happy to try to share sollutions.

Unfortunately I think that your `RemoteCommand` is overwriting what `rsync` is trying to do:

* you call wordmove
* wordmove calls rsync
* rsync will connect through SSH to do things
* once connected it cannot execute anything becouse of the `RemoteCommand`

So, as far as I can see, it won't work.

The problem to continue troubleshooting is that I have no idea about a lot of things there 😜 For example: who is `192.168.95.100`?

Another idea would be to use `docker exec` directly as a transport to `rsync`, but this wuold require a new feature in Wordmove, since it supports only SSH transport whit rsync.

**Comment by alexanderkladov** [comment]
Thanks for getting back to me. `192.168.95.100` is a docker IP that Local by Flywheel reserves for it's own use. All Local by Flywheel sites live under that IP, as far as I can tell, but under different ports.

As I mentioned before, `rsync` works with that IP for file syncing only (no DB stuff), as long as you don't use those last 2 lines from `~/.ssh/config` host alias. But that way the SSH connection lands in docker root and you have to enter a full path like `/Users/alexanderkladov/Local/local_by_flywheel_test/app/public/` for `rsync` to work correctly. Which is fine, but you don't have any access to DB. Whereas if I you could run that `RemoteCommand`, you'd end up in the right docker container and can just use `/app/public/` & have access to all DB files & functions.

Basically the only problem is that I can't get access to each docker container's `mysql` functions from the terminal, without getting into the right docker container first.

With the newest version of Local Lightning (v5+) you can use a DB sockets to connect to the DB and that works perfectly with Wordmove. But I don't want to/can't use that version of **Local Lightning**, since it only supports NGINX and doesn't have Apache. And all of the sites I work with are on Apache/Litespeed servers. So I use their old app **Local by Flywheel** instead. If that sounds confusing, [they have 2 "types" of **Local** app that you can install/run simultaneously](https://localwp.com/help-docs/migrating-from-local-by-flywheel-to-local-lightning/), they both have a very similar in look & feel, but have very different core, where latest app doesn't rely on VirtualBox, while the old one still does.

Hope that makes sense.

**Comment by pioneerskies** [comment]
Yeah, it makes sense. But I strongly feel like `RemoteCommand` is incompatible with `rsync` itself.

I figure 2 possible paths:

### trying to use `docker exec` as an rsync transport

For example

```yml
###################
# Local by Flywheel
###################
<% env_name       = "local_by_flywheel_test" %>
<% vhost          = "https://local_by_flywheel.test" %>
<% wordpress_path = "app/public" %>
<% db_host        = "localhost" %>
<% db_name        = "local" %>
<% db_user        = "root" %>
<% db_pass        = "root" %>
<% ssh_host       = "local_by_flywheel_test" %>
<%= env_name %>: &env_core
  vhost: <%= vhost %>
  wordpress_path: <%= wordpress_path %>
  <<: *defaults
  database:
    host: "<%= db_host %>"
    name: "<%= db_name %>"
    user: "<%= db_user %>"
    password: "<%= db_pass %>"
    port: "<%= db_port %>"
  ssh:
    host: "<%= ssh_host %>"
    rsync_options: '--rsh="docker run -i af8296b4e0e1b228856fcd0bd5d532fd1628df6acda46323e3c701e81a537832"'
```

### Trying some external trickery :D

```yml
###################
# Local by Flywheel
###################
<% env_name       = "local_by_flywheel_test" %>
<% vhost          = "https://local_by_flywheel.test" %>
<% wordpress_path = "app/public" %>
<% db_host        = "localhost" %>
<% db_name        = "local" %>
<% db_user        = "root" %>
<% db_pass        = "root" %>
<% ssh_host       = "local_by_flywheel_test" %>
<%= env_name %>: &env_core
  vhost: <%= vhost %>
  wordpress_path: <%= wordpress_path %>
  <<: *defaults
  database:
    host: "<%= db_host %>"
    name: "<%= db_name %>"
    user: "<%= db_user %>"
    password: "<%= db_pass %>"
    port: "<%= db_port %>"
  ssh:
    host: localhost
    user: docker
    port: 2222
```

In your terminal:

```fish
docker run -e FILTERS={\"id\":[\"^/af8296b4e0e1b228856fcd0bd5d532fd1628df6acda46323e3c701e81a537832$\"]} -e AUTH_MECHANISM=noAuth \
  --name sshd-local_by_flywheel_test -p 2222:22  --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  jeroenpeeters/docker-ssh
```

Then trying to launch wordmove.

P.S.: the snippet is adapted from https://github.com/jeroenpeeters/docker-ssh README and I cannot guarantee it really makes sense 😄
