### ISSUE TITLE
Config autodiscovery

### ISSUE THREAD

**Issue by nlemoine** [welaika/wordmove#601]
Hi @pioneerskies 

Today, tooling is everywhere. This is great but configuring is often tedious and error prone. I often have to repeat some informations multiple times, at multiple locations. An so on when some value changes. 

### `wp-cli` FTW

The whole discussion about adapting wordmove to the WordPress in a subdirectory structure (#597, #590, #591) and the possibilities offered by `wp-cli` gave me some ideas for improvements.

Most, maybe all, config values could be handled automatically by wordmove. 

`wp config get` can grab all the necessary informations to make it work and your `movefile.yaml` file could finally look like: 
```yaml
global:
  sql_adapter: wpcli

local:
  wordpress_path: '/path/to/project' # could event be optional if wordmove.yml is placed inside project root

# would require wp-cli installed on server
production:
  wordpress_path: '/path/to/project' # could event be optional if wordmove.yml is placed inside project root 
  ssh:
    host: host
    user: user
```

Super ideally, it would even grab the different stages from `wp-cli.yml`: https://make.wordpress.org/cli/handbook/running-commands-remotely/

So i could run `wordmove pull -d -e @production`. 

What do you think?
