### ISSUE TITLE
Backslash(es) in rsync options

### ISSUE THREAD

**Issue by martin-josef** [welaika/wordmove#605]
**Describe the bug**
When I use rsync options in the movefile.yml backslashes get introduced into these commands. I run ssh as root. 

The same applies to complex (w symbols) db passwords, even in quotation marks. But I will focus on rsync here.

Example, line in the movefile.yml: 

`rsync_options: "--usermap=www-data --groupmap=www-data --chmod=D770,F660"
`

I have also tried ' instead of ". 

It gets executed as: 

`--usermap\=www-data --groupmap\=www-data --chmod\=D770,F660
`

**Wordmove command**
wordmove push -e staging --all

**Expected behavior**
I expect user- and groupmap / chmod to change ownership and permissions on my staging server, it doesn't (it's not an encoding issue w the log is my guess).

**movefile.yml**

```
global:
  sql_adapter: wpcli

local:
  vhost: http://mysite.test
  wordpress_path: /srv/www/mysite/public_html # use an absolute path here

  database:
    name: mydb
    user: wp
    password: "wp" # could be blank, so always use quotes around
    host: localhost

staging:
  vhost: https://mysite
  wordpress_path: /var/www/mysite/html # use an absolute path here

  database:
    name: dbname
    user: dbuser
    password: "dbpass"
    host: localhost
    # port: 3308 # Use just in case you have exotic server config
    # mysqldump_options: '--max_allowed_packet=1G' # Only available if using SSH
    # mysql_options: '--protocol=TCP' # mysql command is used to import db

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'

  ssh:
    host: ip
    user: root
  #   password: password # password is optional, will use public keys if available.
  #   port: 22 # Port is optional
    rsync_options: "--usermap=www-data --groupmap=www-data --chmod=D770,F660"
```

**Exception/trace**
Paste (removing personal data) the entire trace of error/exception you encountered, if any

**Environment (please complete the following information):**
- OS: macOS 10.15.5
- Ruby: 2.7.1p83
- Wordmove: 5.1.0
- Vagrant 2.2.9
- rsync 3.1.2

**Doctor**
* [x] `wordmove doctor` is all green

Yep, all green. Wordmove pushing / pulling works perfectly except for this issue.
