### ISSUE TITLE
Wordmove Doctor shows errors for socket connection with Local (Flywheel)

### ISSUE THREAD

**Issue by electricarts** [welaika/wordmove#609]
I have problems with the connection to the DB via socket. The movefile section looks like this: 

```
database:
    name: "local"
    user: "root"
    password: "root"
    host: "localhost"
    mysqldump_options:  '--socket "/Users/mario/Library/Application\ Support/Local/run/Q7jGqXSBC/mysql/mysqld.sock"'
    mysql_options:  '--socket "/Users/mario/Library/Application\ Support/Local/run/Q7jGqXSBC/mysql/mysqld.sock"'
```
    

The Doctor says: 

```
❌  error | [/database/mysql_options] key 'mysql_options:' is undefined.

✅  success | `mysql` command is in $PATH

✅  success | `mysqldump` command is in $PATH

❌  error |   We can't connect to the MySQL server using credentials
                specified in the Movefile. Double check them or try
                to debug your system configuration.

                The command used to test was:

                mysql --host=localhost --user=root --password=root -e'QUIT'


❌  error |   We can't connect to the database using credentials
                specified in the Movefile, or the database does not
                exists. Double check them or try to debug your
                system configuration.

                The command used to test was:

                mysql --host=localhost --user=root --password=root local -e'QUIT'
```

I have no idea where else to look. Any idea what I did wrong or what I should change?

macOS 10.15.6
Ruby 2.7.1
Wordmove 5.1.0
Local 5.6.10
