### ISSUE TITLE
Forbid mu-plugins only works with underscored key: mu_plugins

### ISSUE THREAD

**Issue by seanclen** [welaika/wordmove#619]
**Describe the bug**
According to the example configuration in the [movefile.yml-configurations-explained](https://github.com/welaika/wordmove/wiki/movefile.yml-configurations-explained#forbid) article, the key to forbid pushing/pulling must-use plugins is `mu-plugins:`

```yml
production:
  forbid:
    push:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu-plugins: true
    pull:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu-plugins: true
```

However, in my environment, this only works when I use an underscore in the key (`mu_plugins:`). While I can get the operation to behave properly, Doctor will return some errors in the config, see below for details.
```yml
production:
  forbid:
    push:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu_plugins: true
    pull:
      db: false
      plugins: false
      themes: false
      languages: false
      uploads: false
      mu_plugins: true
```

**Wordmove command**
Command used on the CLI: `wordmove pull -e production -m` or `wordmove pull -e production --all`

**Environment (please complete the following information):**
- OS: Ubuntu 18.04.3 LTS
- Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
- Wordmove: 5.2.1

**Doctor**
* [x] `wordmove doctor` is all green with `mu-plugins` key
* [ ]  `[/forbid/push/mu_plugins] key 'mu_plugins:' is undefined.` with `mu_plugins` key
* [ ]  `[/forbid/pull/mu_plugins] key 'mu_plugins:' is undefined.` with `mu_plugins` key
