### ISSUE TITLE
SSH authentication error from msqldump when pushing database (after successful file pushes)

### ISSUE THREAD

**Issue by ThinkByDesign** [welaika/wordmove#621]
So, to be clear, I'm new at wordmove. This is my second site with it, and the first one isn't quite working yet, but for different reasons.

**Describe the bug**

When wordmove gets to the remote dump stage, it generates the error noted below (SSH authentication). What's confusing is that it's just successfully conducted SSH connections to move all the files successfully. I'm also able to ssh directly from the command line, as well as through FileZilla.

When I login to the web server and look at the wp-content directory, I don't see a dump file there. HOWEVER, if I login to the web server (using the credential in the config file) and just run the mysqldump (substituting real values for the secrets omitted in the error), it works, and generates the dump.sql file.

I've also looked at the auth.log for possible clues. When I do a push with --all, I see several chunks like this:
Oct  6 02:22:16 web02 sshd[8898]: Accepted publickey for [correct user] from 99.164.33.88 port 57945 ssh2: [key stuff]
Oct  6 02:22:16 web02 sshd[8898]: pam_unix(sshd:session): session opened for user [correct user] by ([correct uid])
Oct  6 02:22:16 web02 systemd-logind[1422]: New session 82907 of user [correct user].
Oct  6 02:22:17 web02 sshd[8974]: Received disconnect from 99.164.33.88 port 57945:11: disconnected by user
Oct  6 02:22:17 web02 sshd[8974]: Disconnected from user [correct user] 99.164.33.88 port 57945
Oct  6 02:22:17 web02 sshd[8898]: pam_unix(sshd:session): session closed for user [correct user]
Oct  6 02:22:17 web02 systemd-logind[1422]: Removed session 82907.

but then when it tries to do the database thing, it just gets this:
Oct  6 02:22:22 web02 sshd[9364]: Connection closed by authenticating user [correct user - same as above] 99.164.33.88 port 57981 [preauth]

It's almost like it's using different credentials for that step? I do have my ssh config setup to filter by user and apply different keys (I have two logins to the same server with their own keys - both work correctly from the command line, but maybe this code is doing something different?)

Any help would be appreciated!!

**Wordmove command**
wordmove push -e staging -all

**Expected behavior**
Pushing all the files up to the remote staging server (which succeeded).
Pushing database up to the remote server (failed).

**movefile.yml**

```yml
global:
  sql_adapter: wpcli
  #sql_adapter: default #possible alternative if I run into issues
local:
  vhost: http://local.greenmeadowstx.com
  wordpress_path: /Users/kep/Sites/GreenMeadowsTX.com/wordpress # use an absolute path here
  database:
    name: wp_GreenMeadowsTXcom
    user: GreenMeadows
    password: "*************" # could be blank, so always use quotes around
    host: localhost
    mysqldump_options: '--socket /Applications/MAMP/tmp/mysql/mysql.sock'
    mysql_options: '--socket /Applications/MAMP/tmp/mysql/mysql.sock'

staging:
  vhost: https://greenmeadowstx.thinkbydesign.com
  wordpress_path: [absolute path to where wordpress is installed] # use an absolute path here
  
  database:
    name: GreenMeadowsTX_Wordpress
    user: [RemoteUserName]
    password: "[RemotePassword]"
    host: database.visible.ninja
 
  ssh:
    host: web02.visible.ninja
    # User, HostName, Port, and IdentityFile are all set in ~/.ssh/config
    user: [user with full access to the wordpress directory - key files are specified in ssh config and independently tested/working]
    #port: [port number] # Port is optional
    rsync_options: '--verbose --itemize-changes' # Additional rsync options, optional

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'
```

**Exception/trace**

```
   remote | mysqldump --host=[secret] --user=wordpressuser --password=[secret] --result-file="[secret]/wp-content/dump.sql" GreenMeadowsTX_Wordpress
/Users/kep/.rvm/gems/ruby-2.3.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:268:in `start': Authentication failed for user [REDACTED]@web02.visible.ninja (Net::SSH::AuthenticationFailed)
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/photocopier-1.4.0/lib/photocopier/ssh.rb:71:in `session'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/photocopier-1.4.0/lib/photocopier/ssh.rb:44:in `exec!'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:66:in `remote_run'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:79:in `download_remote_db'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:6:in `backup_remote_db!'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:37:in `push_db'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:116:in `block in push'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:40:in `block in handle_options'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `each'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `handle_options'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:115:in `push'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/kep/.rvm/gems/ruby-2.3.0/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
	from /Users/kep/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
	from /Users/kep/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
```

**Environment (please complete the following information):**
- OS: MacOS 11.6
- Ruby: 2.3.0
- Wordmove: 5.2.2

**Doctor**
Reports all green except for 
    ❌  error | [/database/mysql_options] key 'mysql_options:' is undefined.
