### ISSUE TITLE
SPELL_CHECKERS and psych-4.0.6 errors

### ISSUE THREAD

**Issue by marcoluzi** [welaika/wordmove#661]
**Describe the bug**

After updating to macOS Venture, wordmove can not push or pull data from/to the environment. I tried different Ruby Version and reinstalled the wordmove gem multiple times.

**Wordmove command**

`wordmove pull --all` `wordmove push -t`

**Expected behavior**

The commands should run without any errors.

**movefile.yml**

```yml
global:
    sql_adapter: wpcli

local:
    vhost: https://domain.test
    wordpress_path: /Users/user/repos/valet/domain

    database:
        name: domain
        user: user
        host: localhost

beta:
    vhost: https://domain.user.dev
    wordpress_path: /home/user/www/domain.user.dev

    database:
        name: domain
        user: domain
        password:
        host: localhost

    exclude:
        - ".git/"
        - ".gitignore"
        - "node_modules/"
        - "bin/"
        - "tmp/*"
        - "Gemfile*"
        - "Movefile"
        - "movefile"
        - "movefile.yml"
        - "movefile.yaml"
        - "wp-config.php"
        - "wp-content/*.sql.gz"
        - "*.orig"

    ssh:
        host: host
        user: user
        rsync_options: "--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r"

    forbid:
        push:
            db: true
            plugins: true
            themes: false
            languages: true
            uploads: true
            mu_plugins: true
        pull:
            db: false
            plugins: false
            themes: true
            languages: false
            uploads: false
            mu_plugins: false
```

**Exception/trace**

Wordmove returns the following error while pulling:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/user/.gem/ruby/3.1.0/gems/psych-4.0.6/lib/psych.rb:322:in `safe_load': wrong number of arguments (given 4, expected 1) (ArgumentError)
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:30:in `fetch'
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:46:in `environment'
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:34:in `load_dotenv'
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/lib/wordmove/deployer/base.rb:11:in `deployer_for'
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/lib/wordmove/cli.rb:81:in `pull'
        from /Users/user/.gem/ruby/3.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /Users/user/.gem/ruby/3.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/user/.gem/ruby/3.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /Users/user/.gem/ruby/3.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /Users/user/.gem/ruby/3.1.0/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
        from /Users/user/.gem/ruby/3.1.0/bin/wordmove:25:in `load'
        from /Users/user/.gem/ruby/3.1.0/bin/wordmove:25:in `<main>'
```
This part is returned while using any wordmove command, for example `wordmove -v`:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

**Environment (please complete the following information):**

- OS: macOS 13.0 (22A380)
- Ruby: Currently 3.1.0. I also tried 2.6.5, 2.7.6, 3.1.2
- Wordmove: 5.2.2

**Doctor**

`wordmove doctor` returns the same two errors as stated in the Exception/trace section above.
